import { sql } from '@payloadcms/db-postgres'

export type TextileSeedRow = {
  sourceRow: number
  number: number | null
  address: string
  latitude: number
  longitude: number
  company: string
  district: string
}

export const textileCompanies: string[] = ['texcycle', 'm-tex', 'evrotex']

export const textileContainers: TextileSeedRow[] = [
  {
    sourceRow: 1,
    number: 1,
    address: 'ул. Калоян 5',
    latitude: 42.69543,
    longitude: 23.322409,
    company: 'texcycle',
    district: 'Средец',
  },
  {
    sourceRow: 2,
    number: 2,
    address: 'ул. Ген. Гурко 62, от страната на парка, срещу ул. Любен Каравелов',
    latitude: 42.68939,
    longitude: 23.33284,
    company: 'texcycle',
    district: 'Средец',
  },
  {
    sourceRow: 3,
    number: 3,
    address: 'кръстовището на ул. Цар Иван Асен II с ул. Мизия',
    latitude: 42.689144,
    longitude: 23.344159,
    company: 'texcycle',
    district: 'Оборище',
  },
  {
    sourceRow: 4,
    number: 4,
    address: 'ж.к. Белите брези, ул. Лерин – срещу ДГ Брезичка',
    latitude: 42.675249,
    longitude: 23.293521,
    company: 'texcycle',
    district: 'Красно село',
  },
  {
    sourceRow: 5,
    number: 5,
    address: 'ж.к. Хиподрума, ъгъла на ул. Урвич и ул. Булаир',
    latitude: 42.680023,
    longitude: 23.296743,
    company: 'texcycle',
    district: 'Красно село',
  },
  {
    sourceRow: 6,
    number: 6,
    address: 'жк. Борово, бул. Ген. Стефан Тошев, пред бл. 223, вх.А',
    latitude: 42.671354,
    longitude: 23.28328,
    company: 'texcycle',
    district: 'Красно село',
  },
  {
    sourceRow: 7,
    number: 7,
    address: 'ул. Партений Нишавски, Парк Възраждане',
    latitude: 42.696325,
    longitude: 23.307557,
    company: 'texcycle',
    district: 'Възраждане',
  },
  {
    sourceRow: 8,
    number: 8,
    address: 'ул. Цар Симеон, пред ДКЦ 11',
    latitude: 42.703421,
    longitude: 23.308854,
    company: 'texcycle',
    district: 'Възраждане',
  },
  {
    sourceRow: 9,
    number: 9,
    address: 'УНИКРЕДИТ, ул. Гюешево 14, паркинга встрани от Билла',
    latitude: 42.69715,
    longitude: 23.30158,
    company: 'texcycle',
    district: 'Възраждане',
  },
  {
    sourceRow: 10,
    number: 10,
    address: 'ул. Париж 5, на паркинга на Столичен инспекторат',
    latitude: 42.697689,
    longitude: 23.331146,
    company: 'texcycle',
    district: 'Оборище',
  },
  {
    sourceRow: 11,
    number: 11,
    address: 'Парк Заимов, срещу ул. Васил Априлов',
    latitude: 42.69646,
    longitude: 23.34235,
    company: 'texcycle',
    district: 'Оборище',
  },
  {
    sourceRow: 12,
    number: 12,
    address: 'ул. Каймакчалан, вляво от входа на МОЛ Сердика',
    latitude: 42.69241,
    longitude: 23.354802,
    company: 'texcycle',
    district: 'Оборище',
  },
  {
    sourceRow: 13,
    number: 13,
    address: 'бул. Сливница 182, пред Софийска Професионална Гимназия по Туризъм',
    latitude: 42.70442,
    longitude: 23.325817,
    company: 'texcycle',
    district: 'Възраждане',
  },
  {
    sourceRow: 14,
    number: 14,
    address: 'ж.к. Гео Милев, ул. Атанас Узунов – срещу Асикс Арена',
    latitude: 42.684515,
    longitude: 23.364293,
    company: 'texcycle',
    district: 'Слатина',
  },
  {
    sourceRow: 15,
    number: 15,
    address: 'ул. Николай Коперник, пред 22 ДКЦ',
    latitude: 42.67774,
    longitude: 23.360347,
    company: 'texcycle',
    district: 'Слатина',
  },
  {
    sourceRow: 16,
    number: 16,
    address: 'кръстовището на ул. Слатинска и ул. Борис Новоселски, до бл.41 А',
    latitude: 42.687755,
    longitude: 23.371406,
    company: 'texcycle',
    district: 'Слатина',
  },
  {
    sourceRow: 17,
    number: 17,
    address: 'ж.к. Изгрев, бул. Цариградско шосе, вляво от Билла на ул. Фредерик Жолио Кюри',
    latitude: 42.67534,
    longitude: 23.358419,
    company: 'texcycle',
    district: 'Изгрев',
  },
  {
    sourceRow: 18,
    number: 18,
    address: 'ул. Златовръх срещу №1',
    latitude: 42.67464,
    longitude: 23.334,
    company: 'texcycle',
    district: 'Лозенец',
  },
  {
    sourceRow: 19,
    number: 19,
    address: 'пл. проф. Васил Геров',
    latitude: 42.682364,
    longitude: 23.325706,
    company: 'texcycle',
    district: 'Триадица',
  },
  {
    sourceRow: 20,
    number: 20,
    address: 'жк. Хладилника, пазар Сребърна',
    latitude: 42.66036,
    longitude: 23.318103,
    company: 'texcycle',
    district: 'Лозенец',
  },
  {
    sourceRow: 21,
    number: 21,
    address: 'Южен парк, вход от ул. Нишава',
    latitude: 42.66976,
    longitude: 23.303832,
    company: 'texcycle',
    district: 'Триадица',
  },
  {
    sourceRow: 22,
    number: 22,
    address: 'жк. Гоце Делчев, кръстовището на ул. Костенски водопад с бул. Гоце Делчев, до бл.102',
    latitude: 42.666423,
    longitude: 23.300544,
    company: 'texcycle',
    district: 'Триадица',
  },
  {
    sourceRow: 23,
    number: 23,
    address: 'кръстовището на бул. Гоце Делчев с бул. България, до пешеходния подлез',
    latitude: 42.672434,
    longitude: 23.293976,
    company: 'texcycle',
    district: 'Триадица',
  },
  {
    sourceRow: 24,
    number: 24,
    address: 'ул. Алеко Туранджа и ул. Хъшове, до ЦДГ Коледарче',
    latitude: 42.699148,
    longitude: 23.290147,
    company: 'texcycle',
    district: 'Красна поляна',
  },
  {
    sourceRow: 25,
    number: 25,
    address: 'жк. Лагера, ул. Балчик, до 25 ОУ',
    latitude: 42.681133,
    longitude: 23.286334,
    company: 'texcycle',
    district: 'Красно село',
  },
  {
    sourceRow: 26,
    number: 26,
    address: 'ул. Виктор Палов до Т-Маркет – спирка Вардар на метрото',
    latitude: 42.70641,
    longitude: 23.28484,
    company: 'texcycle',
    district: 'Илинден',
  },
  {
    sourceRow: 27,
    number: 27,
    address: 'ул. Габрово, до бл.374',
    latitude: 42.710159,
    longitude: 23.300021,
    company: 'texcycle',
    district: 'Илинден',
  },
  {
    sourceRow: 28,
    number: 28,
    address: 'ул. Република, до 137 ОДЗ „Калина Малина“',
    latitude: 42.732003,
    longitude: 23.310308,
    company: 'texcycle',
    district: 'Надежда',
  },
  {
    sourceRow: 29,
    number: 29,
    address: 'паркинга на бл. 172, до метростанция Надежда',
    latitude: 42.72715,
    longitude: 23.30141,
    company: 'texcycle',
    district: 'Надежда',
  },
  {
    sourceRow: 30,
    number: 30,
    address: 'Северен парк, входа откъм Надежда, до обръщача',
    latitude: 42.73937,
    longitude: 23.30335,
    company: 'texcycle',
    district: 'Надежда',
  },
  {
    sourceRow: 31,
    number: 31,
    address: 'бул. Кръстьо Пастухов, ъгъла с ул. Тирана, на входа на Парк Езерото',
    latitude: 42.662207,
    longitude: 23.397442,
    company: 'texcycle',
    district: 'Искър',
  },
  {
    sourceRow: 32,
    number: 32,
    address: 'Цариградски комплекс, бл. 285 /В',
    latitude: 42.64736,
    longitude: 23.401194,
    company: 'texcycle',
    district: 'Искър',
  },
  {
    sourceRow: 33,
    number: 33,
    address: 'жк. Дружба – бул. Цветан Лазаров, до храм „Св.Пророк Илия 2“',
    latitude: 42.655119,
    longitude: 23.399704,
    company: 'texcycle',
    district: 'Искър',
  },
  {
    sourceRow: 34,
    number: 34,
    address: 'бул. Александър Малинов и бул. Атанас Москов (до магазин Хит)',
    latitude: 42.641238,
    longitude: 23.372969,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 35,
    number: 35,
    address: 'бул. Свето Преображение – срещу сградата на районна администрация Младост',
    latitude: 42.640909,
    longitude: 23.380704,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 36,
    number: 36,
    address: 'ул. Ресен, до 145 ОУ',
    latitude: 42.648231,
    longitude: 23.384672,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 37,
    number: 37,
    address: 'Метростанция Бизнес Парк, до буферен паркинг',
    latitude: 42.628852,
    longitude: 23.373459,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 38,
    number: 38,
    address:
      'МЛАДОСТ 1 – до подлеза на кръстовището на ул.“Димитър Моллов“ и локалното Цариградско шосе',
    latitude: 42.662475,
    longitude: 23.376131,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 39,
    number: 39,
    address:
      'МЛАДОСТ 4 – ул.“Атанас Москов“, след кръстовището с ул.“Ал.Паскалев“ спирка посока Бизнес парк',
    latitude: 42.635072,
    longitude: 23.374926,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 40,
    number: 40,
    address: 'кв. Княжево, площад Сред село',
    latitude: 42.66081,
    longitude: 23.242946,
    company: 'texcycle',
    district: 'Витоша',
  },
  {
    sourceRow: 41,
    number: 41,
    address: 'кв. Драгалевци, спирка кв. Драгалевци',
    latitude: 42.629083,
    longitude: 23.309487,
    company: 'texcycle',
    district: 'Витоша',
  },
  {
    sourceRow: 42,
    number: 42,
    address: 'бул. Симеоновско шосе, до спирката',
    latitude: 42.612267,
    longitude: 23.339092,
    company: 'texcycle',
    district: 'Витоша',
  },
  {
    sourceRow: 43,
    number: 43,
    address: 'кв. Бояна, спирката до Боянско ханче',
    latitude: 42.64649,
    longitude: 23.267196,
    company: 'texcycle',
    district: 'Витоша',
  },
  {
    sourceRow: 44,
    number: 44,
    address: 'кв. Манастирски ливади, обръщача на ТБ2 – спирката',
    latitude: 42.659218,
    longitude: 23.272876,
    company: 'texcycle',
    district: 'Витоша',
  },
  {
    sourceRow: 45,
    number: 45,
    address: 'кв. Манастирски ливади, ул. Казбек 59А',
    latitude: 42.665696,
    longitude: 23.284945,
    company: 'texcycle',
    district: 'Витоша',
  },
  {
    sourceRow: 46,
    number: 46,
    address: 'бул. Царица Йоанна, паркинг Била и метростанция Люлин',
    latitude: 42.718792,
    longitude: 23.25676,
    company: 'texcycle',
    district: 'Люлин',
  },
  {
    sourceRow: 47,
    number: 47,
    address: 'бул. Райко Даскалов 5, Люлин 4',
    latitude: 42.71357,
    longitude: 23.24644,
    company: 'texcycle',
    district: 'Люлин',
  },
  {
    sourceRow: 48,
    number: 48,
    address: 'Люлин 10, бул. Луи Пастьор, до бл. 101',
    latitude: 42.715067,
    longitude: 23.267211,
    company: 'texcycle',
    district: 'Люлин',
  },
  {
    sourceRow: 49,
    number: 49,
    address: 'жк. Банишора, ул. Опълченска 117, бл. 37, вх. В',
    latitude: 42.711996,
    longitude: 23.314445,
    company: 'texcycle',
    district: 'Сердика',
  },
  {
    sourceRow: 50,
    number: 50,
    address: 'ул. Иван Хаджийски, срещу 149 СОУ',
    latitude: 42.686322,
    longitude: 23.247092,
    company: 'texcycle',
    district: 'Овча купел',
  },
  {
    sourceRow: 51,
    number: 51,
    address: 'ул. Любляна 38, пазарчето под Фантастико',
    latitude: 42.671169,
    longitude: 23.259138,
    company: 'texcycle',
    district: 'Овча купел',
  },
  {
    sourceRow: 52,
    number: 52,
    address: 'бул. Президент Линкълн, до спирка „пазара Овча купел“',
    latitude: 42.686574,
    longitude: 23.255546,
    company: 'texcycle',
    district: 'Овча купел',
  },
  {
    sourceRow: 53,
    number: 53,
    address: 'ул. Тодорини кукли 47, до Т-Маркет',
    latitude: 42.684128,
    longitude: 23.241579,
    company: 'texcycle',
    district: 'Подуяне',
  },
  {
    sourceRow: 54,
    number: 54,
    address: 'ул. Тодорини кукли, спирката до ДМ',
    latitude: 42.702086,
    longitude: 23.354842,
    company: 'texcycle',
    district: 'Подуяне',
  },
  {
    sourceRow: 55,
    number: 55,
    address: 'кръстовището на ул. Златен клас с ул. Асен Трайков, до Т-Маркет',
    latitude: 42.73831,
    longitude: 23.29498,
    company: 'texcycle',
    district: 'Връбница',
  },
  {
    sourceRow: 56,
    number: 56,
    address: 'с. Челопечене, площада',
    latitude: 42.73199,
    longitude: 23.476029,
    company: 'texcycle',
    district: 'Кремиковци',
  },
  {
    sourceRow: 57,
    number: 57,
    address: 'с. Горни Богров, до кметството',
    latitude: 42.719278,
    longitude: 23.529757,
    company: 'texcycle',
    district: 'Кремиковци',
  },
  {
    sourceRow: 58,
    number: 58,
    address: 'с. Бистрица, площада',
    latitude: 42.586447,
    longitude: 23.360402,
    company: 'texcycle',
    district: 'Панчарево',
  },
  {
    sourceRow: 59,
    number: 59,
    address: 'с. Кривина, ул. Розова градина, на площада',
    latitude: 42.680355,
    longitude: 23.465201,
    company: 'texcycle',
    district: 'Панчарево',
  },
  {
    sourceRow: 60,
    number: 60,
    address: 'ул. Цар Симеон 1',
    latitude: 42.705471,
    longitude: 23.148053,
    company: 'texcycle',
    district: 'Банкя',
  },
  {
    sourceRow: 61,
    number: 61,
    address: 'ул. Цар Освободител 1',
    latitude: 42.705801,
    longitude: 23.150936,
    company: 'texcycle',
    district: 'Банкя',
  },
  {
    sourceRow: 62,
    number: 62,
    address: 'Мусагеница – ул. Полк. Г.Янков, до 8 СУ „Васил Левски“',
    latitude: 42.662258,
    longitude: 23.363312,
    company: 'texcycle',
    district: 'Студентски',
  },
  {
    sourceRow: 63,
    number: 63,
    address: 'жк.Дървеница – ул. Бели мел, зад Фантастико',
    latitude: 42.654,
    longitude: 23.360852,
    company: 'texcycle',
    district: 'Студентски',
  },
  {
    sourceRow: 64,
    number: 64,
    address: 'жк. Младост 1 – ул. Въртопо, пред бл. 85',
    latitude: 42.663941,
    longitude: 23.367948,
    company: 'texcycle',
    district: 'Младост',
  },
  {
    sourceRow: 65,
    number: 65,
    address:
      'Дианабад – кръстовището на бул. Г.М.Димитров и ул. Никола Габровски, до бензиностанция Шел',
    latitude: 42.660042,
    longitude: 23.347566,
    company: 'texcycle',
    district: 'Изгрев',
  },
  {
    sourceRow: 66,
    number: 66,
    address: 'с. Негован, ул. Васил Левски, на площада',
    latitude: 42.768989,
    longitude: 23.404968,
    company: 'texcycle',
    district: 'Нови Искър',
  },
  {
    sourceRow: 67,
    number: null,
    address: 'Надежда София ул. Садина до бл.507 вх Б',
    latitude: 42.64223,
    longitude: 23.414667,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 68,
    number: null,
    address: 'Надежда София ул Делийска Воденица 421 до ОУ 150 Цар Семион Велики',
    latitude: 42.646734,
    longitude: 23.409202,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 69,
    number: null,
    address: 'ж.к.Дружба 2 кръстовището бл.312А-бл.315',
    latitude: 42.648199,
    longitude: 23.407602,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 70,
    number: null,
    address: 'ж.к. Дружба 2, ул. Ханс Кристиан Андерсен',
    latitude: 42.650177,
    longitude: 23.400309,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 71,
    number: null,
    address: 'При 4 ОУ - ул.“Тирана“22  и ул.“5048“',
    latitude: 42.660444,
    longitude: 23.399968,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 72,
    number: null,
    address: 'ж.к. Дружба 1 ул. 5019-та',
    latitude: 42.666122,
    longitude: 23.397157,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 73,
    number: null,
    address: 'ул. "Капитан Димитър Списаревски", 1592 7-ми 11-ти километър',
    latitude: 42.660381,
    longitude: 23.394546,
    company: 'm-tex',
    district: 'Искър',
  },
  {
    sourceRow: 74,
    number: null,
    address: 'ул.Йеросалим 8',
    latitude: 42.658404,
    longitude: 23.378058,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 75,
    number: null,
    address: 'ул.Йеросалим 22 до Фантастико',
    latitude: 42.655467,
    longitude: 23.374179,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 76,
    number: null,
    address: 'ул.Методи Андонов 74',
    latitude: 42.653171,
    longitude: 23.372122,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 77,
    number: null,
    address: '1784 Младост 1, ресторант пицария ПРАДО',
    latitude: 42.651754,
    longitude: 23.374472,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 78,
    number: null,
    address: 'бул. Андрей Сахаров 4 China sity',
    latitude: 42.651036,
    longitude: 23.376833,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 79,
    number: null,
    address: 'ул.“Ана Ахматова“ до №532',
    latitude: 42.650917,
    longitude: 23.384607,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 80,
    number: null,
    address: 'ул. Ген. Радко Димитриев',
    latitude: 42.645478,
    longitude: 23.383176,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 81,
    number: null,
    address: 'ул. Бъднина 303',
    latitude: 42.645279,
    longitude: 23.379575,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 82,
    number: null,
    address: 'ж.к. Младост  4, ул.Александър Паскалев',
    latitude: 42.63525,
    longitude: 23.379989,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 83,
    number: null,
    address: 'ж.к. Младост  4, ул.Божан Ангелов',
    latitude: 42.633333,
    longitude: 23.378099,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 84,
    number: null,
    address: 'ж.к. Младост  4, ул.Божан Ангелов 426',
    latitude: 42.63319,
    longitude: 23.375385,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 85,
    number: null,
    address: 'ул. Проф.Александър Танев 469',
    latitude: 42.627173,
    longitude: 23.383914,
    company: 'm-tex',
    district: 'Младост',
  },
  {
    sourceRow: 86,
    number: null,
    address: 'ул. "Витошка зорница", 1415 Водолей-1',
    latitude: 42.636599,
    longitude: 23.310911,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 87,
    number: null,
    address: 'ул. Витошка Зорница до Фантастико',
    latitude: 42.639582,
    longitude: 23.312751,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 88,
    number: null,
    address: 'бул. Симеоновска шосе 166',
    latitude: 42.615156,
    longitude: 23.338593,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 89,
    number: null,
    address: 'ул. Акад. Борис Стефанов 58',
    latitude: 42.644056,
    longitude: 23.342008,
    company: 'm-tex',
    district: 'Студентски',
  },
  {
    sourceRow: 90,
    number: null,
    address: 'ул. Акад. Стефан Младенов 80',
    latitude: 42.644931,
    longitude: 23.345101,
    company: 'm-tex',
    district: 'Студентски',
  },
  {
    sourceRow: 91,
    number: null,
    address: 'ул.  Проф д-р Иван Странски  до бл.61',
    latitude: 42.642932,
    longitude: 23.343674,
    company: 'm-tex',
    district: 'Студентски',
  },
  {
    sourceRow: 92,
    number: null,
    address: 'ул. Никола Габровски 22 кв. Дианабад',
    latitude: 42.663269,
    longitude: 23.34453,
    company: 'm-tex',
    district: 'Изгрев',
  },
  {
    sourceRow: 93,
    number: null,
    address: 'София Център ул.Любен Каравелов 25',
    latitude: 42.687156,
    longitude: 23.329683,
    company: 'm-tex',
    district: 'Средец',
  },
  {
    sourceRow: 94,
    number: null,
    address: 'ул. Гео Милев 18',
    latitude: 42.684978,
    longitude: 23.357179,
    company: 'm-tex',
    district: 'Слатина',
  },
  {
    sourceRow: 95,
    number: null,
    address: 'ж.к. Иван Вазов, бул. Петко Каравелов 77',
    latitude: 42.678912,
    longitude: 23.31341,
    company: 'm-tex',
    district: 'Триадица',
  },
  {
    sourceRow: 96,
    number: null,
    address: 'ж.к. Гоце Делчев, ул. 406-та №5',
    latitude: 42.660407,
    longitude: 23.300684,
    company: 'm-tex',
    district: 'Триадица',
  },
  {
    sourceRow: 97,
    number: null,
    address: 'ул. Васил Стефанов 58',
    latitude: 42.655428,
    longitude: 23.288546,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 98,
    number: null,
    address: 'кв. Манастирски ливади, ул. „Иван Киров" до City Home Park',
    latitude: 42.661596,
    longitude: 23.289134,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 99,
    number: null,
    address: 'кв. Манастирски ливади,ул. Ралевица 75',
    latitude: 42.658684,
    longitude: 23.280501,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 100,
    number: null,
    address: 'кв. Манастирски ливади,ул. Ралевица 84',
    latitude: 42.661214,
    longitude: 23.283138,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 101,
    number: null,
    address: 'кв. Манастирски ливади,ул. Пирин 65',
    latitude: 42.665007,
    longitude: 23.281986,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 102,
    number: null,
    address: 'кв. Манастирски ливади,ул. Казбек 57',
    latitude: 42.666198,
    longitude: 23.281811,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 103,
    number: null,
    address: 'кв. Манастирски ливади,ул. Витошка зорница 3',
    latitude: 42.639582,
    longitude: 23.312751,
    company: 'm-tex',
    district: 'Витоша',
  },
  {
    sourceRow: 104,
    number: null,
    address: 'ж.к Лагера ул. Житница',
    latitude: 42.679349,
    longitude: 23.284073,
    company: 'm-tex',
    district: 'Красно село',
  },
  {
    sourceRow: 105,
    number: null,
    address: 'кв. Овча купел, ул. Президент Линкълн -метростанция',
    latitude: 42.683071,
    longitude: 23.270644,
    company: 'm-tex',
    district: 'Овча купел',
  },
  {
    sourceRow: 106,
    number: null,
    address: 'кв. Овча купел ул. братя Прошек',
    latitude: 42.684277,
    longitude: 23.248293,
    company: 'm-tex',
    district: 'Овча купел',
  },
  {
    sourceRow: 107,
    number: null,
    address: 'кв. Овча купел, ул. Промишлена бл.402',
    latitude: 42.685001,
    longitude: 23.250618,
    company: 'm-tex',
    district: 'Овча купел',
  },
  {
    sourceRow: 108,
    number: null,
    address: 'кв. Овча купел, ул.761-ва',
    latitude: 42.683969,
    longitude: 23.256667,
    company: 'm-tex',
    district: 'Овча купел',
  },
  {
    sourceRow: 109,
    number: null,
    address: 'кв. Овча купел, ул.Буземска 2 до парк',
    latitude: 42.678639,
    longitude: 23.267639,
    company: 'm-tex',
    district: 'Овча купел',
  },
  {
    sourceRow: 110,
    number: null,
    address: 'кв. Овча купел, бул. „Овча купел“11,София',
    latitude: 42.673503,
    longitude: 23.269777,
    company: 'm-tex',
    district: 'Овча купел',
  },
  {
    sourceRow: 111,
    number: null,
    address: 'бул. Константин Величков 61',
    latitude: 42.702344,
    longitude: 23.297987,
    company: 'm-tex',
    district: 'Възраждане',
  },
  {
    sourceRow: 112,
    number: null,
    address: 'ж.к. Илинден бул. Вардар',
    latitude: 42.702981,
    longitude: 23.285755,
    company: 'm-tex',
    district: 'Илинден',
  },
  {
    sourceRow: 113,
    number: null,
    address: 'ж.к. Люлин 7, ул. Полк. Стоян Топузов 722',
    latitude: 42.710762,
    longitude: 23.263103,
    company: 'm-tex',
    district: 'Люлин',
  },
  {
    sourceRow: 114,
    number: null,
    address: 'ж.к. Люлин 7, ул. Златопласт 810',
    latitude: 42.721668,
    longitude: 23.260897,
    company: 'm-tex',
    district: 'Люлин',
  },
  {
    sourceRow: 115,
    number: null,
    address: 'ж.к. Люлин 9, ул. „ген. Никола Генев“',
    latitude: 42.717972,
    longitude: 23.265177,
    company: 'm-tex',
    district: 'Люлин',
  },
  {
    sourceRow: 116,
    number: null,
    address: 'ж.к. Люлин - Център, 1324 София',
    latitude: 42.717921,
    longitude: 23.257534,
    company: 'm-tex',
    district: 'Люлин',
  },
  {
    sourceRow: 117,
    number: null,
    address: 'кв. Надежда ул. Възрожденска 71',
    latitude: 42.729121,
    longitude: 23.295131,
    company: 'm-tex',
    district: 'Надежда',
  },
  {
    sourceRow: 118,
    number: null,
    address: 'ж.к. Надежда 1, ул. „Село Кръвеник“ 15-17',
    latitude: 42.727885,
    longitude: 23.299456,
    company: 'm-tex',
    district: 'Надежда',
  },
  {
    sourceRow: 119,
    number: null,
    address: 'ул. Никола Котков и ул. Княз Иван Кулин',
    latitude: 42.726935,
    longitude: 23.30001,
    company: 'm-tex',
    district: 'Надежда',
  },
  {
    sourceRow: 120,
    number: null,
    address: 'кв. Орландовци, ул. Капиновски манастир 1',
    latitude: 42.720712,
    longitude: 23.333605,
    company: 'm-tex',
    district: 'Сердика',
  },
  {
    sourceRow: 121,
    number: null,
    address: 'кв. Требич, ул. Леденика 12 до 63 ОУ Христо Ботев',
    latitude: 42.774756,
    longitude: 23.313113,
    company: 'm-tex',
    district: 'Надежда',
  },
  {
    sourceRow: 122,
    number: null,
    address: 'кв Изгрев - бул. Г.М.Димитров, Kaufland',
    latitude: 42.66774,
    longitude: 23.365953,
    company: 'm-tex',
    district: 'Изгрев',
  },
  {
    sourceRow: 123,
    number: 1,
    address: 'ул. „Цар Симеон“ № 1',
    latitude: 42.705471,
    longitude: 23.148053,
    company: 'evrotex',
    district: 'Банкя',
  },
  {
    sourceRow: 124,
    number: 2,
    address: 'ул. „Цар Освободител“ № 1',
    latitude: 42.705801,
    longitude: 23.150936,
    company: 'evrotex',
    district: 'Банкя',
  },
  {
    sourceRow: 125,
    number: 3,
    address: 'с. Иваняне, до кметството',
    latitude: 42.706298,
    longitude: 23.18133,
    company: 'evrotex',
    district: 'Банкя',
  },
  {
    sourceRow: 126,
    number: 4,
    address: 'кв. Княжево, площад Сред село',
    latitude: 42.660818,
    longitude: 23.242946,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 127,
    number: 5,
    address: 'кв. Драгалевци, спирка кв. Драгалевци',
    latitude: 42.629083,
    longitude: 23.309487,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 128,
    number: 6,
    address: 'бул. „Симеоновско шосе“, спирка кв. „Симеоново“',
    latitude: 42.612267,
    longitude: 23.339092,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 129,
    number: 7,
    address: 'кв. Бояна, спирката до Боянско ханче',
    latitude: 42.64649,
    longitude: 23.267196,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 130,
    number: 8,
    address: 'ж.к. Бъкстон, обръщалото на тролей №   2',
    latitude: 42.659218,
    longitude: 23.272876,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 131,
    number: 9,
    address: 'кв. „Манастирски ливади“, ул. „Казбек“ № 59А',
    latitude: 42.665696,
    longitude: 23.284945,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 132,
    number: 10,
    address: 'ж.к Павлово, ъгъла на ул. Казбек до бл. 11 и ул. Ген. Ал. Суворов',
    latitude: 42.668931,
    longitude: 23.274994,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 133,
    number: 11,
    address: 'с. Владая, ул. Войнишко въстание до читалището',
    latitude: 42.628908,
    longitude: 23.196045,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 134,
    number: 12,
    address: 'ъгъла на ул. Белмекен с ул. Мусала, пред 55 ДЯ',
    latitude: 42.667903,
    longitude: 23.268514,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 135,
    number: 13,
    address: 'бул.Цар Борис III, обръщалото на автобус 58',
    latitude: 42.658829,
    longitude: 23.240721,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 136,
    number: 14,
    address: 'кръстовището на ул."Златен клас" с ул."Асен Трайков", до Т Маркет',
    latitude: 42.73831,
    longitude: 23.29498,
    company: 'evrotex',
    district: 'Връбница',
  },
  {
    sourceRow: 137,
    number: 15,
    address: 'кв. Връбница 2 - ул."Тричко Велев", обръщалото на автобус 285',
    latitude: 42.739277,
    longitude: 23.290783,
    company: 'evrotex',
    district: 'Връбница',
  },
  {
    sourceRow: 138,
    number: 16,
    address: 'с. Мрамор, ул. "Васил Левски", градинката пред кметсвото',
    latitude: 42.785459,
    longitude: 23.273757,
    company: 'evrotex',
    district: 'Връбница',
  },
  {
    sourceRow: 139,
    number: 17,
    address: 'ул. „Партений Нишавски“, парк Възраждане',
    latitude: 42.696325,
    longitude: 23.307557,
    company: 'evrotex',
    district: 'Възраждане',
  },
  {
    sourceRow: 140,
    number: 18,
    address: 'ул. „Цар Симеон“ пред ДКЦ 11',
    latitude: 42.703421,
    longitude: 23.308854,
    company: 'evrotex',
    district: 'Възраждане',
  },
  {
    sourceRow: 141,
    number: 19,
    address: 'Ул. „Гюешево“ № 14, Уникредит, паркинга встрани от Била',
    latitude: 42.69715,
    longitude: 23.30158,
    company: 'evrotex',
    district: 'Възраждане',
  },
  {
    sourceRow: 142,
    number: 20,
    address:
      'кръстовището на ул."Зайчар" с бул."Ал.Стамболисйки", пред Национален дворец на децата',
    latitude: 42.700312,
    longitude: 23.298797,
    company: 'evrotex',
    district: 'Възраждане',
  },
  {
    sourceRow: 143,
    number: 21,
    address: 'ъгъла на ул."Пиротска" с бул."инж. Иван Иванов"',
    latitude: 42.702434,
    longitude: 23.303371,
    company: 'evrotex',
    district: 'Възраждане',
  },
  {
    sourceRow: 144,
    number: 22,
    address: 'ж.к. Изгрев, бул. „Цариградско шосе“, вляво от Билла на ул. „Фредерик Жолио Кюри',
    latitude: 42.67534,
    longitude: 23.358419,
    company: 'evrotex',
    district: 'Изгрев',
  },
  {
    sourceRow: 145,
    number: 23,
    address: 'Кръстовището на бул. „Г. М. Димитров“ и ул. „Никола Габровски“ до бензиностанция ШЕЛ',
    latitude: 42.660042,
    longitude: 23.347566,
    company: 'evrotex',
    district: 'Изгрев',
  },
  {
    sourceRow: 146,
    number: 24,
    address: 'кв. Дианабад, ул."Васил Калчев" до 105 СУ "Атанас Далчев"',
    latitude: 42.663935,
    longitude: 23.349723,
    company: 'evrotex',
    district: 'Изгрев',
  },
  {
    sourceRow: 147,
    number: 25,
    address: 'ул."Пиер Дегейтър", детска площадка до супермаркет "Изток"',
    latitude: 42.669598,
    longitude: 23.357995,
    company: 'evrotex',
    district: 'Изгрев',
  },
  {
    sourceRow: 148,
    number: 26,
    address: 'ул. „Виктор Палов“ до Т- Маркет  - спирка Вардар на метрото',
    latitude: 42.706412,
    longitude: 23.28484,
    company: 'evrotex',
    district: 'Илинден',
  },
  {
    sourceRow: 149,
    number: 27,
    address: 'бул. Сливница 236',
    latitude: 42.71083,
    longitude: 23.2924,
    company: 'evrotex',
    district: 'Илинден',
  },
  {
    sourceRow: 150,
    number: 28,
    address: 'ул."Габрово", до бл.374',
    latitude: 42.710159,
    longitude: 23.300021,
    company: 'evrotex',
    district: 'Илинден',
  },
  {
    sourceRow: 151,
    number: 29,
    address:
      'ж.к. Света Тройца, ъгъла на ул.Насте Стоянов и ул. Цар Иван Александър, до магазин Била',
    latitude: 42.707634,
    longitude: 23.295007,
    company: 'evrotex',
    district: 'Илинден',
  },
  {
    sourceRow: 152,
    number: 30,
    address: 'Цариградски комплекс, бл. 285 В',
    latitude: 42.647363,
    longitude: 23.401194,
    company: 'evrotex',
    district: 'Искър',
  },
  {
    sourceRow: 153,
    number: 31,
    address: 'бул. „Кръстьо Пастухов“, ъгъла на ул. „Тирана, на входа на парк Езерото',
    latitude: 42.662207,
    longitude: 23.397442,
    company: 'evrotex',
    district: 'Искър',
  },
  {
    sourceRow: 154,
    number: 32,
    address: 'Дружба - бул. "Цветан Лазаров", до църквата',
    latitude: 42.655119,
    longitude: 23.399704,
    company: 'evrotex',
    district: 'Искър',
  },
  {
    sourceRow: 155,
    number: 33,
    address: 'жк. Дружба, ул. "5038", до Т-Маркет',
    latitude: 42.669663,
    longitude: 23.389977,
    company: 'evrotex',
    district: 'Искър',
  },
  {
    sourceRow: 156,
    number: 34,
    address: 'жк. Дружба, ул. "5041", зад бл.108',
    latitude: 42.66751,
    longitude: 23.391851,
    company: 'evrotex',
    district: 'Искър',
  },
  {
    sourceRow: 157,
    number: 35,
    address: 'ул. Алеко Туранджа“ и ул. „Хъшове“ до ЦДГ Коледарче',
    latitude: 42.699148,
    longitude: 23.290147,
    company: 'evrotex',
    district: 'Красна поляна',
  },
  {
    sourceRow: 158,
    number: 36,
    address: 'ул."Добротич" 329 А, след кръстовището с бул."Никола Мушанов"',
    latitude: 42.692707,
    longitude: 23.282032,
    company: 'evrotex',
    district: 'Красна поляна',
  },
  {
    sourceRow: 159,
    number: 37,
    address: 'кръстовището на бул."Ал.Стамболийски" с ул."Булина ливада", до Фантастико',
    latitude: 42.70219,
    longitude: 23.283367,
    company: 'evrotex',
    district: 'Красна поляна',
  },
  {
    sourceRow: 160,
    number: 38,
    address: 'бул."Александър Стамболийски", до 10 ДКЦ',
    latitude: 42.701485,
    longitude: 23.291885,
    company: 'evrotex',
    district: 'Красна поляна',
  },
  {
    sourceRow: 161,
    number: 39,
    address: 'кръстовището на ул. Румяна с ул. Стария войн, до бл.24-Ж',
    latitude: 42.696886,
    longitude: 23.283013,
    company: 'evrotex',
    district: 'Красна поляна',
  },
  {
    sourceRow: 162,
    number: 40,
    address: 'ул. Суходолска до бл. 124В',
    latitude: 42.700726,
    longitude: 23.278682,
    company: 'evrotex',
    district: 'Красна поляна',
  },
  {
    sourceRow: 163,
    number: 41,
    address: 'ул."Боговец", до Районен Съд',
    latitude: 42.685236,
    longitude: 23.295664,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 164,
    number: 42,
    address: 'ж.к. „Белите брези“, ул. „Лерин“, срещу ДГ Брезичка',
    latitude: 42.675249,
    longitude: 23.293521,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 165,
    number: 43,
    address: 'ж.к. „Хиподрума“, ъгъла на ул. „Урвич“ и ул. „Булаир“',
    latitude: 42.680023,
    longitude: 23.296743,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 166,
    number: 44,
    address: 'Борово - бул. Ген. Стефан Тошев , пред бл.223, вх. А',
    latitude: 42.671354,
    longitude: 23.28328,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 167,
    number: 45,
    address: 'бул. Гоце Делчев ъгъла с бул. България срещу вход-изход на пешеходен подлез',
    latitude: 42.672434,
    longitude: 23.293976,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 168,
    number: 46,
    address: 'ж.к. Лагера, ул.Хайдушка поляна,бл.4 срещу  Балкантон',
    latitude: 42.683682,
    longitude: 23.287439,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 169,
    number: 47,
    address: 'жк. Лагера – ул. Балчик, до  25 ОУ',
    latitude: 42.681133,
    longitude: 23.286334,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 170,
    number: 48,
    address: 'ж.к. Борово, ул.Солун 25, пред бл.34',
    latitude: 42.672433,
    longitude: 23.291899,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 171,
    number: 49,
    address: 'ж.к. Борово, ъгъла на ул. Солун с ул.Невестина скала, пред бл. 13 А, вх.А',
    latitude: 42.668527,
    longitude: 23.286933,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 172,
    number: 50,
    address: 'бул. Тодор Каблешков, подход към пешеходен подлез',
    latitude: 42.665868,
    longitude: 23.287454,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 173,
    number: 51,
    address: 'ж.к. Хиподрума, ул. Булаир, алея към ОКИ Красно село',
    latitude: 42.682437,
    longitude: 23.293118,
    company: 'evrotex',
    district: 'Красно село',
  },
  {
    sourceRow: 174,
    number: 52,
    address: 'ж.к. Бъктон, бул.Братя Бъкстон до бл.5',
    latitude: 42.671217,
    longitude: 23.277078,
    company: 'evrotex',
    district: 'Витоша',
  },
  {
    sourceRow: 175,
    number: 53,
    address: 'с. Челопечене - площада',
    latitude: 42.73199,
    longitude: 23.476029,
    company: 'evrotex',
    district: 'Кремиковци',
  },
  {
    sourceRow: 176,
    number: 54,
    address: 'с. Горни Богров, до кметството',
    latitude: 42.719278,
    longitude: 23.529757,
    company: 'evrotex',
    district: 'Кремиковци',
  },
  {
    sourceRow: 177,
    number: 55,
    address: 'ул. „Златовръх“ срещу № 1',
    latitude: 42.674645,
    longitude: 23.334,
    company: 'evrotex',
    district: 'Лозенец',
  },
  {
    sourceRow: 178,
    number: 56,
    address: 'площад проф. Васил Геров',
    latitude: 42.682364,
    longitude: 23.325706,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 179,
    number: 57,
    address: 'ж.к. Хладилника, пазар Сребърна',
    latitude: 42.660363,
    longitude: 23.318103,
    company: 'evrotex',
    district: 'Лозенец',
  },
  {
    sourceRow: 180,
    number: 58,
    address: 'пл. Хелзинки, ул."Димитър Хаджикоцев"',
    latitude: 42.67775,
    longitude: 23.32119,
    company: 'evrotex',
    district: 'Лозенец',
  },
  {
    sourceRow: 181,
    number: 59,
    address: 'бул."Черни връх", метростанция Европейски съюз, посока НДК',
    latitude: 42.679196,
    longitude: 23.32189,
    company: 'evrotex',
    district: 'Лозенец',
  },
  {
    sourceRow: 182,
    number: 60,
    address: 'бул. Хр. Смирненски 2',
    latitude: 42.685309,
    longitude: 23.330577,
    company: 'evrotex',
    district: 'Лозенец',
  },
  {
    sourceRow: 183,
    number: 61,
    address: 'ул. Милин Камък 3',
    latitude: 42.684074,
    longitude: 23.326887,
    company: 'evrotex',
    district: 'Лозенец',
  },
  {
    sourceRow: 184,
    number: 62,
    address: 'Люлин 4, бул. „Райко Даскалов“ №5',
    latitude: 42.71357,
    longitude: 23.24644,
    company: 'evrotex',
    district: 'Люлин',
  },
  {
    sourceRow: 185,
    number: 63,
    address: 'Бул. „Царица Йоана“, паркинг Била и метростанция Люлин',
    latitude: 42.718792,
    longitude: 23.25676,
    company: 'evrotex',
    district: 'Люлин',
  },
  {
    sourceRow: 186,
    number: 64,
    address: 'Люлин 9 бул. "Луи Пастьор", до бл.101',
    latitude: 42.715067,
    longitude: 23.267211,
    company: 'evrotex',
    district: 'Люлин',
  },
  {
    sourceRow: 187,
    number: 65,
    address: 'бул. „Александър Малинов“ и ул. д-р „Атанас Москов“ до магазин ХИТ',
    latitude: 42.641238,
    longitude: 23.372969,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 188,
    number: 66,
    address: 'бул. Свето Преображение“ срещу сградата на районна администрация Младост',
    latitude: 42.640909,
    longitude: 23.380704,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 189,
    number: 67,
    address:
      'до подлеза на кръстовището на ул. „Димитър Моллов“ и локалното платно на бул. „Цариградско шосе“',
    latitude: 42.662475,
    longitude: 23.376131,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 190,
    number: 68,
    address:
      'ул. „Атанас Москов“ след кръстовището с ул. „Ал. Паскалев“ спирката посока Бизнес парк',
    latitude: 42.635072,
    longitude: 23.374926,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 191,
    number: 69,
    address: 'ул. „Ресен“, до 145 ОУ',
    latitude: 42.648231,
    longitude: 23.384672,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 192,
    number: 70,
    address: 'Метростанция -Бизнес парк – на тротоара до буферния паркинг',
    latitude: 42.628852,
    longitude: 23.373459,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 193,
    number: 71,
    address: 'ж.к. Младост 1, ул. Никола Генадиев , до трафопоста до 125 СУ',
    latitude: 42.653169,
    longitude: 23.37814,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 194,
    number: 72,
    address: 'кв. Младост 3, ул."Бъднина", пред 144 СУ "Народни будители"',
    latitude: 42.642804,
    longitude: 23.377676,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 195,
    number: 73,
    address: 'ул. проф.д-р Васил Златарски, трафопоста до бл.221',
    latitude: 42.643467,
    longitude: 23.37276,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 196,
    number: 74,
    address: 'кв. Горубляне, ъгъла на бул. Самоковско шосе и ул. Петър Дипларов',
    latitude: 42.626614,
    longitude: 23.406901,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 197,
    number: 75,
    address: 'ул. „Република“, до 137 ОДЗ Калина Малина',
    latitude: 42.732003,
    longitude: 23.310308,
    company: 'evrotex',
    district: 'Надежда',
  },
  {
    sourceRow: 198,
    number: 76,
    address: 'паркинга на бл. 172, до метростанция Надежда',
    latitude: 42.72715,
    longitude: 23.30141,
    company: 'evrotex',
    district: 'Надежда',
  },
  {
    sourceRow: 199,
    number: 77,
    address: 'Централен вход на Северен парк, до обръщалото на автобус № 86',
    latitude: 42.73937,
    longitude: 23.30335,
    company: 'evrotex',
    district: 'Надежда',
  },
  {
    sourceRow: 200,
    number: 78,
    address: 'кв. Илиенци, площада на ул."Жасмин" и бул."Рожен"',
    latitude: 42.750978,
    longitude: 23.318027,
    company: 'evrotex',
    district: 'Надежда',
  },
  {
    sourceRow: 201,
    number: 79,
    address: 'кв. Требич -ул."Латин Колев", Паметник на загиналите',
    latitude: 42.772696,
    longitude: 23.316201,
    company: 'evrotex',
    district: 'Надежда',
  },
  {
    sourceRow: 202,
    number: 80,
    address: 'с. Негован – ул. Васил Левски / площад/',
    latitude: 42.768989,
    longitude: 23.404968,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 203,
    number: 81,
    address: 'с.Мировяне, ул."Чавдар Войвода", пред читалище Христо Ботев',
    latitude: 42.790947,
    longitude: 23.304259,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 204,
    number: 82,
    address: 'с.Кубратово, ул. "Куманица" , срещу кметството',
    latitude: 42.772766,
    longitude: 23.362085,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 205,
    number: 83,
    address: 'НОВИ ИСКЪР - кв. Курило, ул. Чавдар войвода, до Пощата',
    latitude: 42.822451,
    longitude: 23.354284,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 206,
    number: 84,
    address: 'НОВИ ИСКЪР - кв. Гниляне, площад Гнилянска република',
    latitude: 42.808857,
    longitude: 23.376268,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 207,
    number: 85,
    address: 'НОВИ ИСКЪР - с. Подгумер, площад Васил Левски',
    latitude: 42.802756,
    longitude: 23.403911,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 208,
    number: 86,
    address: 'НОВИ ИСКЪР - с. Локорско, площад Чавдарци',
    latitude: 42.795619,
    longitude: 23.447044,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 209,
    number: 87,
    address: 'НОВИ ИСКЪР - с. Доброславци, площад Мегдана',
    latitude: 42.821538,
    longitude: 23.282703,
    company: 'evrotex',
    district: 'Нови Искър',
  },
  {
    sourceRow: 210,
    number: 88,
    address: 'ул. „Париж“ № 5 на паркинга на Столичен инспекторат',
    latitude: 42.697689,
    longitude: 23.331146,
    company: 'evrotex',
    district: 'Оборище',
  },
  {
    sourceRow: 211,
    number: 89,
    address: 'Парк Заимов, срещу ул. „Васил Априлов“',
    latitude: 42.6966,
    longitude: 23.34254,
    company: 'evrotex',
    district: 'Оборище',
  },
  {
    sourceRow: 212,
    number: 90,
    address: 'ул. „Каймачалан“, вляво от входа на МОЛ Сердика',
    latitude: 42.692411,
    longitude: 23.354802,
    company: 'evrotex',
    district: 'Оборище',
  },
  {
    sourceRow: 213,
    number: 91,
    address: 'ъгъла на бул. Сливница с ул. Веслец',
    latitude: 42.70445,
    longitude: 23.32559,
    company: 'evrotex',
    district: 'Възраждане',
  },
  {
    sourceRow: 214,
    number: 92,
    address: 'ъгъла на ул."Ангиста" с ул."Кешан", до ЛИДЛ',
    latitude: 42.703893,
    longitude: 23.334758,
    company: 'evrotex',
    district: 'Оборище',
  },
  {
    sourceRow: 215,
    number: 93,
    address: 'ул. „ Иван Хаджийски“ срещу 149 СОУ',
    latitude: 42.686322,
    longitude: 23.247092,
    company: 'evrotex',
    district: 'Овча купел',
  },
  {
    sourceRow: 216,
    number: 94,
    address: 'кръстовището на ул. Любляна с ул. Народен герой',
    latitude: 42.671564,
    longitude: 23.260362,
    company: 'evrotex',
    district: 'Овча купел',
  },
  {
    sourceRow: 217,
    number: 95,
    address: 'бул. „Президент Линкълн“ , спирка "Пазара Овча Купел"',
    latitude: 42.686574,
    longitude: 23.255546,
    company: 'evrotex',
    district: 'Овча купел',
  },
  {
    sourceRow: 218,
    number: 96,
    address: 'кв. Суходол, ул. "Бъдеще", пред магазин Фреш маркет',
    latitude: 42.696156,
    longitude: 23.227013,
    company: 'evrotex',
    district: 'Овча купел',
  },
  {
    sourceRow: 219,
    number: 97,
    address: 'с. Бистрица, площада',
    latitude: 42.586447,
    longitude: 23.360402,
    company: 'evrotex',
    district: 'Панчарево',
  },
  {
    sourceRow: 220,
    number: 98,
    address: 'с. Кривина, ул. Розова градина, на площада',
    latitude: 42.680355,
    longitude: 23.465201,
    company: 'evrotex',
    district: 'Панчарево',
  },
  {
    sourceRow: 221,
    number: 99,
    address: 'с. Кокаляне, ъгъла на ул. Искър с ул. Кръстан Младенов',
    latitude: 42.577012,
    longitude: 23.414534,
    company: 'evrotex',
    district: 'Панчарево',
  },
  {
    sourceRow: 222,
    number: 100,
    address: 'ул. „Тодорини кукли“ № 47, до Т-Маркет',
    latitude: 42.704359,
    longitude: 23.366565,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 223,
    number: 101,
    address: 'ул."Тодорини кукли", спирката до ДМ',
    latitude: 42.702086,
    longitude: 23.354842,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 224,
    number: 102,
    address: 'кв. "Левски В" - ул."Поп Грую" срещу бл.9',
    latitude: 42.708782,
    longitude: 23.380417,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 225,
    number: 103,
    address: 'кв. "Левски Г" - ул."Г.Кюмюрджиев" между 199 ОУ и 91 ОДЗ',
    latitude: 42.713776,
    longitude: 23.377171,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 226,
    number: 104,
    address: 'кв. "Левски Г" - ул."Г.Кюмюрджиев" срещу бл.29',
    latitude: 42.713031,
    longitude: 23.387106,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 227,
    number: 105,
    address: 'кв." Стефан Караджа" - ул."Васил Кънчев" , спирката до бл.142',
    latitude: 42.706867,
    longitude: 23.357795,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 228,
    number: 106,
    address: 'кв." Хаджи Димитър" - ул."Резбарска" до бл.100',
    latitude: 42.708675,
    longitude: 23.343833,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 229,
    number: 107,
    address: 'кв." Хаджи Димитър" - ул."Никола Войновски" до 42 ОУ',
    latitude: 42.706641,
    longitude: 23.345008,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 230,
    number: 108,
    address: 'ж.к. Сухата река,  ул. Тодорини кукли, срещу Била',
    latitude: 42.702082,
    longitude: 23.359135,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 231,
    number: 109,
    address: 'ъгъла на ул. Сава Цонев с ул. Емануил Васкидович, пред 44 СУ Неофит Бозвели',
    latitude: 42.701452,
    longitude: 23.368026,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 232,
    number: 110,
    address: 'ъгъла на бул. Ботевградско шосе с ул. Вършец, бл.6, вх.А',
    latitude: 42.699887,
    longitude: 23.370897,
    company: 'evrotex',
    district: 'Подуяне',
  },
  {
    sourceRow: 233,
    number: 111,
    address: 'ж.к. Банишора, ул. „Опълченска“ № 117, бл. 37, вх. В',
    latitude: 42.711996,
    longitude: 23.314445,
    company: 'evrotex',
    district: 'Сердика',
  },
  {
    sourceRow: 234,
    number: 112,
    address: 'кв. Орландовци, ул."Железопътна" 18, до Билла',
    latitude: 42.717684,
    longitude: 23.342967,
    company: 'evrotex',
    district: 'Сердика',
  },
  {
    sourceRow: 235,
    number: 113,
    address: 'кв. "Банишора", кръстовището на ул."Ген.Иван Чернаев" и ул."Подполковник Калитин"',
    latitude: 42.709211,
    longitude: 23.311016,
    company: 'evrotex',
    district: 'Сердика',
  },
  {
    sourceRow: 236,
    number: 114,
    address: 'кв." Банишора", бул." Ген. Николай Г. Столетов" 5А',
    latitude: 42.711901,
    longitude: 23.311969,
    company: 'evrotex',
    district: 'Сердика',
  },
  {
    sourceRow: 237,
    number: 115,
    address: 'ж.к. „Гео Милев“, ул. Атанас Узунов“, срещу Асикс Арена',
    latitude: 42.684515,
    longitude: 23.364293,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 238,
    number: 116,
    address: 'ул. Николай Коперник пред 22 ДКЦ',
    latitude: 42.67774,
    longitude: 23.360347,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 239,
    number: 117,
    address: 'кръстовището на ул."Слатинска" и ул."Борис Новоселски", до бл.41 А',
    latitude: 42.687755,
    longitude: 23.371406,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 240,
    number: 118,
    address: 'ул." Гео Милев", спирка "Слатина"',
    latitude: 42.680456,
    longitude: 23.372742,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 241,
    number: 119,
    address: 'ул."Николай Коперник", спирката до 93 СУ "Ал. Теодоров-Балан"',
    latitude: 42.681886,
    longitude: 23.362338,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 242,
    number: 120,
    address: 'бул."Шипченски приход", пред зала "Универсиада"',
    latitude: 42.68137,
    longitude: 23.356288,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 243,
    number: 121,
    address: 'кръстовището на ул."Коста Лулчев" и ул."Ал. Вон Хумболт"',
    latitude: 42.676482,
    longitude: 23.36296,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 244,
    number: 122,
    address: 'ул. Кутловица, пред 23 СУ  Фредерик Ж.Кюри',
    latitude: 42.695116,
    longitude: 23.356506,
    company: 'evrotex',
    district: 'Слатина',
  },
  {
    sourceRow: 245,
    number: 123,
    address: 'ул. „Калоян“ № 5',
    latitude: 42.69543,
    longitude: 23.322409,
    company: 'evrotex',
    district: 'Средец',
  },
  {
    sourceRow: 246,
    number: 124,
    address: 'ул. „ген. Гурко“ № 62 срещу ул. „Любен Каравелов“ от страната на парка',
    latitude: 42.68939,
    longitude: 23.33284,
    company: 'evrotex',
    district: 'Средец',
  },
  {
    sourceRow: 247,
    number: 125,
    address: 'ул. „Иван Асен II“  с ул. „Мизия“',
    latitude: 42.689144,
    longitude: 23.344159,
    company: 'evrotex',
    district: 'Оборище',
  },
  {
    sourceRow: 248,
    number: 126,
    address: 'ул. полк. Г. Янков“ до 8-мо СУ „Васил Левски“',
    latitude: 42.662258,
    longitude: 23.363312,
    company: 'evrotex',
    district: 'Студентски',
  },
  {
    sourceRow: 249,
    number: 127,
    address: 'жк. Дървеница- ул."Бели мел", зад Фантастико',
    latitude: 42.654,
    longitude: 23.360852,
    company: 'evrotex',
    district: 'Студентски',
  },
  {
    sourceRow: 250,
    number: 128,
    address: 'ж.к. „Младост 1“ /сектор 5/ - ул. „Въртопо“ срещу бл. 85',
    latitude: 42.663941,
    longitude: 23.367948,
    company: 'evrotex',
    district: 'Младост',
  },
  {
    sourceRow: 251,
    number: 129,
    address: 'Студенстки град, ул."Ак. Стефан Младенов" 8',
    latitude: 42.65288,
    longitude: 23.347201,
    company: 'evrotex',
    district: 'Студентски',
  },
  {
    sourceRow: 252,
    number: 130,
    address:
      'кв. Мусагеница - кръстовището на ул. Белимел и ул. проф. Стоян Киркович, до 72 ДГ и пред бл.40, вх. Д',
    latitude: 42.651348,
    longitude: 23.363783,
    company: 'evrotex',
    district: 'Студентски',
  },
  {
    sourceRow: 253,
    number: 131,
    address: 'кв. Малинова долина, ул. проф. Живко Сталев, зад бл.23',
    latitude: 42.63706,
    longitude: 23.341039,
    company: 'evrotex',
    district: 'Студентски',
  },
  {
    sourceRow: 254,
    number: 132,
    address: 'Южен парк, вход от ул. „Нишава“',
    latitude: 42.669761,
    longitude: 23.303832,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 255,
    number: 133,
    address: 'ул. Костенски водопад до бл. 102 и ъгъла с бул. Гоце Делчев',
    latitude: 42.666423,
    longitude: 23.300544,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 256,
    number: 134,
    address: 'ул."Костенски подопад" до бл.247',
    latitude: 42.66181,
    longitude: 23.29561,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 257,
    number: 135,
    address: 'бул."Петко Ю. Тодоров", подлез срещу пазар Иван Вазов',
    latitude: 42.676331,
    longitude: 23.303142,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 258,
    number: 136,
    address: 'бул."Прага", до плувен басейн "Мадара"',
    latitude: 42.687672,
    longitude: 23.31145,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 259,
    number: 137,
    address: 'кв. Стрелбище, кръстовището на ул. Орехова гора с бул. Гоце Делчев, до ТОТО пункта',
    latitude: 42.669355,
    longitude: 23.297802,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 260,
    number: 138,
    address: 'кв. Стрелбище, ул. Тулча до читалище "Светлина 1940"',
    latitude: 42.673609,
    longitude: 23.229645,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 261,
    number: 139,
    address: 'кръстовището на бул."Тодор Каблешков" с ул."Деян Белишки"',
    latitude: 42.659848,
    longitude: 23.298994,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 262,
    number: 140,
    address: 'ул. Орехова гора, пред ДГ Звънче',
    latitude: 42.668415,
    longitude: 23.295734,
    company: 'evrotex',
    district: 'Триадица',
  },
  {
    sourceRow: 263,
    number: 141,
    address: 'ж.к. Мотописта, до 121 СУ Георги Измерлиев',
    latitude: 42.665504,
    longitude: 23.29369,
    company: 'evrotex',
    district: 'Триадица',
  },
]

type QueryResultRow = Record<string, unknown>

/**
 * Minimal structural type satisfied by a Drizzle executor: the pooled
 * `payload.db.drizzle` instance, a transaction handle, and the `db` argument
 * Payload passes to migrations all match this shape.
 */
export interface DrizzleExecutor {
  execute(query: ReturnType<typeof sql>): Promise<{ rows: QueryResultRow[] }>
}

function getFirstId(rows: QueryResultRow[]): number | null {
  const value = rows[0]?.id

  if (typeof value === 'number') return value
  if (typeof value === 'string') return Number(value)

  return null
}

/**
 * Insert the companies and their containers. Re-running is safe: companies are
 * upserted by name, and a container is matched on (company, address, location)
 * so a second run updates the existing row instead of duplicating it.
 */
export async function seedTextileContainerRows(tx: DrizzleExecutor): Promise<number> {
  const companyIds = new Map<string, number>()
  const districtIds = new Map<string, number>()

  const getDistrictId = async (districtName?: string): Promise<number | null> => {
    if (!districtName) return null

    const cached = districtIds.get(districtName)
    if (cached) return cached

    const result = await tx.execute(sql`
      SELECT id
      FROM city_districts
      WHERE LOWER(TRIM(name)) = LOWER(TRIM(${districtName}))
      LIMIT 1
    `)

    const id = getFirstId(result.rows as QueryResultRow[])
    if (!id) return null

    districtIds.set(districtName, id)
    return id
  }

  const upsertCompany = async (name: string): Promise<number> => {
    const cached = companyIds.get(name)
    if (cached) return cached

    const result = await tx.execute(sql`
      INSERT INTO textile_companies (name, updated_at, created_at)
      VALUES (${name}, NOW(), NOW())
      ON CONFLICT (name)
      DO UPDATE SET updated_at = NOW()
      RETURNING id
    `)

    const id = getFirstId(result.rows as QueryResultRow[])
    if (!id) throw new Error(`Could not create or resolve textile company: "${name}"`)

    companyIds.set(name, id)
    return id
  }

  for (const company of textileCompanies) {
    await upsertCompany(company)
  }

  for (const container of textileContainers) {
    const companyId = await upsertCompany(container.company)
    const districtId = await getDistrictId(container.district)

    const existing = await tx.execute(sql`
      SELECT id FROM textile_containers
      WHERE company_id = ${companyId}
        AND address = ${container.address}
        AND ST_Equals(location, ST_SetSRID(ST_MakePoint(${container.longitude}, ${container.latitude}), 4326))
      LIMIT 1
    `)

    const existingId = getFirstId(existing.rows as QueryResultRow[])

    if (existingId) {
      await tx.execute(sql`
        UPDATE textile_containers
        SET number = ${container.number},
            -- COALESCE so a district set by hand in the admin UI is not wiped
            -- by a re-run of the seed for a row that carries no district name.
            district_id = COALESCE(${districtId}, district_id),
            updated_at = NOW()
        WHERE id = ${existingId}
      `)
      continue
    }

    await tx.execute(sql`
      INSERT INTO textile_containers (
        number,
        district_id,
        company_id,
        address,
        location,
        status,
        notes,
        updated_at,
        created_at
      )
      VALUES (
        ${container.number},
        ${districtId},
        ${companyId},
        ${container.address},
        ST_SetSRID(ST_MakePoint(${container.longitude}, ${container.latitude}), 4326),
        NULL,
        NULL,
        NOW(),
        NOW()
      )
    `)
  }

  return textileContainers.length
}
