import config from '@payload-config'
import { sql } from '@payloadcms/db-postgres'
import { getPayload } from 'payload'

type FountainStatus =
  | 'Добро'
  | 'За възстановяване'
  | 'За ремонт'
  | 'За основен ремонт'
  | 'Отлично'
  | 'Задоволително'
  | 'Незадоволително'
  | 'Не работи'
  | 'Няма информация'

type ActivationType = 'Бутон' | 'Кран' | 'Да' | 'Не'

type FountainSeedRow = {
  publicNumber: string
  district: string
  address: string
  latitude: number
  longitude: number
  source: string | null
  protectionStatus: string | null
  isActive: boolean | null
  status: FountainStatus
  owner: string | null
  activationType: ActivationType | null
}

const fountains: FountainSeedRow[] = [
  {
    publicNumber: 'DF-RSR-0001',
    district: 'Средец',
    address: 'Храм "Св. София" – чешма за питейна вода',
    latitude: 42.696557,
    longitude: 23.330718,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0002',
    district: 'Средец',
    address: 'Храм "Св. Седмочисленици" – чешма за питейна вода',
    latitude: 42.69021404,
    longitude: 23.32723721,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSR-0003',
    district: 'Средец',
    address: 'Градина "Св. Кл. Охридски" – чешма за питейна вода',
    latitude: 42.694333,
    longitude: 23.334444,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RSR-0004',
    district: 'Средец',
    address: 'Градина "Св. Кл. Охридски" – чешма за питейна вода',
    latitude: 42.694556,
    longitude: 23.333694,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RSR-0005',
    district: 'Средец',
    address: 'Борисова градина – чешма "Розариум" за питейна вода',
    latitude: 42.687984,
    longitude: 23.337096,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0006',
    district: 'Средец',
    address: 'Борисова градина – чешма "Шестицата" за питейна вода',
    latitude: 42.688416,
    longitude: 23.338819,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0007',
    district: 'Средец',
    address: 'Борисова градина – чешма детска площадка за питейна вода',
    latitude: 42.687196,
    longitude: 23.339002,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0008',
    district: 'Средец',
    address: 'Борисова градина – чешма "Лилиите" за питейна вода',
    latitude: 42.685101,
    longitude: 23.342949,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSR-0009',
    district: 'Средец',
    address: 'Борисова градина – чешма "Читалнята" за питейна вода',
    latitude: 42.68347,
    longitude: 23.344198,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSR-0010',
    district: 'Средец',
    address: 'Борисова градина – чешма "Обсерваторията" за питейна вода',
    latitude: 42.681689,
    longitude: 23.345349,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSR-0011',
    district: 'Средец',
    address: 'Борисова градина – чешма "Полиграфията" за питейна вода',
    latitude: 42.686771,
    longitude: 23.341938,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: null,
  },
  {
    publicNumber: 'DF-RSR-0012',
    district: 'Средец',
    address: 'Народен театър – чешма за питейна вода',
    latitude: 42.694749,
    longitude: 23.324887,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RSR-0013',
    district: 'Средец',
    address: 'Народен театър – чешма за питейна вода',
    latitude: 42.6953013,
    longitude: 23.3252454,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: null,
    status: 'За ремонт',
    owner: null,
    activationType: null,
  },
  {
    publicNumber: 'DF-RSR-0014',
    district: 'Средец',
    address: 'БНБ',
    latitude: 42.695735,
    longitude: 23.324889,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSR-0015',
    district: 'Средец',
    address: 'НХГ Тамплиери',
    latitude: 42.696726,
    longitude: 23.326626,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSR-0016',
    district: 'Средец',
    address: 'НХГ Етнографски музей',
    latitude: 42.696236,
    longitude: 23.328354,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSR-0017',
    district: 'Средец',
    address: 'Руска Черква',
    latitude: 42.695859,
    longitude: 23.329239,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSR-0018',
    district: 'Средец',
    address: 'Гр. Кристал',
    latitude: 42.694467,
    longitude: 23.329647,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0019',
    district: 'Средец',
    address: 'Св Патр. Евтимий',
    latitude: 42.688356,
    longitude: 23.328427,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0020',
    district: 'Средец',
    address: 'пл. Райко Даскалов',
    latitude: 42.692363,
    longitude: 23.322673,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSR-0021',
    district: 'Средец',
    address: 'пред хотел "Рила"',
    latitude: 42.694952,
    longitude: 23.323063,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSR-0022',
    district: 'Средец',
    address: 'Княжевска градина',
    latitude: 42.690329,
    longitude: 23.3339378,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSR-0023',
    district: 'Средец',
    address: 'Площад "Португалия"',
    latitude: 42.6900267,
    longitude: 23.341982,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RVA-0001',
    district: 'Възраждане',
    address: 'Парк "Възраждане" – чешма светофар за питейна вода',
    latitude: 42.695931,
    longitude: 23.308608,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RVA-0002',
    district: 'Възраждане',
    address: 'Парк "Възраждане" – чешма до база за питейна вода',
    latitude: 42.693967,
    longitude: 23.306637,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RVA-0003',
    district: 'Възраждане',
    address: 'Парк "Възраждане" – чешма до фонтана за питейна вода',
    latitude: 42.694922,
    longitude: 23.306689,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RVA-0004',
    district: 'Възраждане',
    address: 'Парк "Възраждане" – чешма нова част I за питейна вода',
    latitude: 42.696265,
    longitude: 23.306256,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RVA-0005',
    district: 'Възраждане',
    address: 'Парк "Възраждане" – чешма нова част II за питейна вода',
    latitude: 42.695921,
    longitude: 23.305613,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RLO-0001',
    district: 'Лозенец',
    address: 'Пазар "Стара стена" – чешма за питейна вода',
    latitude: 42.683903,
    longitude: 23.329889,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: null,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RLO-0002',
    district: 'Лозенец',
    address: 'Баня Лозенец – чешма "Морената" за питейна вода',
    latitude: 42.68276,
    longitude: 23.32246,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RVR-0001',
    district: 'Връбница',
    address: 'Пазар "Връбница" – чешма за питейна вода',
    latitude: 42.735781,
    longitude: 23.290755,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Няма информация',
    owner: null,
    activationType: null,
  },
  {
    publicNumber: 'DF-RVR-0002',
    district: 'Връбница',
    address: 'Бакърени гробища – чешма за питейна вода',
    latitude: 42.73244,
    longitude: 23.280754,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Няма информация',
    owner: null,
    activationType: null,
  },
  {
    publicNumber: 'DF-RVR-0003',
    district: 'Връбница',
    address: 'Ж.к. Връбница 2, ул. Бели Дунав, бл.632',
    latitude: 42.73667,
    longitude: 23.29222,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'Собственост на Пазари „Север“',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RVR-0004',
    district: 'Връбница',
    address: 'С.Мрамор, ул. Васил Левски - център',
    latitude: 42.7854,
    longitude: 23.2747,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Отлично',
    owner: 'Софийска вода',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RVR-0005',
    district: 'Връбница',
    address: 'С.Мрамор – гробищен парк (2 броя чешми)',
    latitude: 42.806,
    longitude: 23.2765,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'Софийска вода',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RVR-0006',
    district: 'Връбница',
    address: 'С.Мрамор, до Фреш маркет',
    latitude: 42.78609,
    longitude: 23.27394,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Не работи',
    owner: 'водомер на Фреш Маркет',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RVR-0007',
    district: 'Връбница',
    address: 'С.Мрамор, ул. Мичур срещу № 56Б',
    latitude: 42.7882,
    longitude: 23.2688,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: null,
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RVR-0008',
    district: 'Връбница',
    address: 'С.Мрамор, ул. Мичур №49',
    latitude: 42.7862,
    longitude: 23.273,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: null,
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RVR-0009',
    district: 'Връбница',
    address: 'С.Волуяк, ул. Зорница № 67',
    latitude: 42.7738,
    longitude: 23.2432,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: null,
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RVR-0010',
    district: 'Връбница',
    address: 'С.Волуяк, ул. Зорница № 49',
    latitude: 42.7739,
    longitude: 23.2433,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'Водомер на църква Свети Георги Победоносец',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RVR-0011',
    district: 'Връбница',
    address: 'С.Волуяк- гробищен парк',
    latitude: 42.7795,
    longitude: 23.2368,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'Водомер на църква Света Петка',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RVR-0012',
    district: 'Връбница',
    address: 'С.Волуяк, ул.Зорница № 22',
    latitude: 42.7694,
    longitude: 23.2442,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'кметството',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RIZ-0001',
    district: 'Изгрев',
    address: 'пред сградата на районната администрация на ул. "Атанас Далчев" №12',
    latitude: 42.671519,
    longitude: 23.354266,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RIZ-0002',
    district: 'Изгрев',
    address: 'на детска площадка пред блок 45 в жк. "Дианабад"',
    latitude: 42.664245,
    longitude: 23.352669,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RIZ-0003',
    district: 'Изгрев',
    address: 'на алея Яворов" до тенис кортовете в парк "Борисова градина"',
    latitude: 42.677791,
    longitude: 23.346343,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RIL-0001',
    district: 'Илинден',
    address: 'Парк "Света Троица"',
    latitude: 42.705409,
    longitude: 23.295081,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RIL-0002',
    district: 'Илинден',
    address: 'Вход на Западен парк - до спирка на градски транспорт',
    latitude: 42.714991,
    longitude: 23.283317,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Не работи',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RIL-0003',
    district: 'Илинден',
    address: 'Западен парк, на централната алея до първия кръг',
    latitude: 42.713875,
    longitude: 23.281329,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Незадоволително',
    owner: 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RIL-0004',
    district: 'Илинден',
    address: 'Западен парк, на централната алея, до зона за скара',
    latitude: 42.710303,
    longitude: 23.277098,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Незадоволително',
    owner: 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RIL-0005',
    district: 'Илинден',
    address: 'Западен парк, на централната алея, до детска площадка',
    latitude: 42.709908,
    longitude: 23.276342,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Незадоволително',
    owner: 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RIL-0006',
    district: 'Илинден',
    address: 'Западен парк, на алея до криви огледала',
    latitude: 42.711278,
    longitude: 23.282407,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Незадоволително',
    owner: 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RIL-0007',
    district: 'Илинден',
    address: 'Бул. "Сливница", на ъгъла с ул. "Кукуш" ("Вентова чешма")',
    latitude: 42.715201,
    longitude: 23.284081,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Не работи',
    owner: 'Не се поддържа',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RNA-0001',
    district: 'Надежда',
    address: 'Парк "Надежда" в ж.к."Лев Толстой"',
    latitude: 42.722344,
    longitude: 23.309273,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0002',
    district: 'Надежда',
    address: 'ж.к."Надежда" -1ч., бул."Ломско шосе" до метростанция "Надежда"',
    latitude: 42.727772,
    longitude: 23.300934,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RNA-0003',
    district: 'Надежда',
    address: 'ж.к."Надежда" -1ч., бул."Ломско шосе" № 36 пред магазин "DM"',
    latitude: 42.726369,
    longitude: 23.302936,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0004',
    district: 'Надежда',
    address: 'ж.к."Свобода", Северен парк до кучешка площадка',
    latitude: 42.740109,
    longitude: 23.302319,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0005',
    district: 'Надежда',
    address: 'Северен парк, до детска площадка "Морско дъно"',
    latitude: 42.740202,
    longitude: 23.298026,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0006',
    district: 'Надежда',
    address: 'Северен парк - централен вход от към ул."Ген. Никола Жеков"',
    latitude: 42.738618,
    longitude: 23.298916,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0007',
    district: 'Надежда',
    address: 'Северен парк до "Китайска беседка"',
    latitude: 42.739989,
    longitude: 23.299172,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0008',
    district: 'Надежда',
    address: 'Северен парк до "Амфи театър"',
    latitude: 42.741449,
    longitude: 23.303725,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0009',
    district: 'Надежда',
    address: 'ж.к."Надежда" - 3ч., до метростанция "Бели Дунав"',
    latitude: 42.73483,
    longitude: 23.292836,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNA-0010',
    district: 'Надежда',
    address: 'ж.к."Надежда"-2ч., до бл.261',
    latitude: 42.732506,
    longitude: 23.299514,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Не работи',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0001',
    district: 'Нови Искър',
    address: 'с.Балша - площад "Център"',
    latitude: 42.848833,
    longitude: 23.269222,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RNI-0002',
    district: 'Нови Искър',
    address: 'с.Балша - гробищен парк',
    latitude: 42.844833,
    longitude: 23.268444,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0003',
    district: 'Нови Искър',
    address: 'с.Балша ул.Ст.планина - последна спирка',
    latitude: 42.854556,
    longitude: 23.264722,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0004',
    district: 'Нови Искър',
    address: 'с.Доброславци - гробищен парк',
    latitude: 42.823083,
    longitude: 23.288944,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0005',
    district: 'Нови Искър',
    address: 'с.Доброславци - център',
    latitude: 42.822028,
    longitude: 23.283139,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0006',
    district: 'Нови Искър',
    address: 'с.Житен - площад "Център"',
    latitude: 42.818194,
    longitude: 23.250917,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0007',
    district: 'Нови Искър',
    address: 'с.Житен - гробищен парк',
    latitude: 42.815583,
    longitude: 23.257278,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0008',
    district: 'Нови Искър',
    address: 'с.Мировяне - ул."Ал.Константинов"',
    latitude: 42.788861,
    longitude: 23.305,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RNI-0009',
    district: 'Нови Искър',
    address: 'с.Мировяне - гробищен парк',
    latitude: 42.797917,
    longitude: 23.297556,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0010',
    district: 'Нови Искър',
    address: 'с.Кътина - площад център',
    latitude: 42.81425,
    longitude: 23.350639,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0011',
    district: 'Нови Искър',
    address: 'с.Кътина - градинка център',
    latitude: 42.8455,
    longitude: 23.319278,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0012',
    district: 'Нови Искър',
    address: 'с.Кътина - при детска площадка ул.Езеро',
    latitude: 42.843583,
    longitude: 23.322111,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0013',
    district: 'Нови Искър',
    address: 'с.Подгумер - парк "Изгрев"',
    latitude: 42.80275,
    longitude: 23.405722,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0014',
    district: 'Нови Искър',
    address: 'с.Подгумер - гробищен парк',
    latitude: 42.803944,
    longitude: 23.403694,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0015',
    district: 'Нови Искър',
    address: 'с.Подгумер - площад "Център"',
    latitude: 42.802944,
    longitude: 23.403583,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0016',
    district: 'Нови Искър',
    address: 'с.Войнеговци - площад "Център"',
    latitude: 42.804278,
    longitude: 23.40725,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0017',
    district: 'Нови Искър',
    address: 'с.Войнеговци - стадион',
    latitude: 42.798583,
    longitude: 23.424028,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0018',
    district: 'Нови Искър',
    address: 'с.Войнеговци - гробищен парк',
    latitude: 42.798333,
    longitude: 23.421611,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0019',
    district: 'Нови Искър',
    address: 'с.Локорско - гробищен парк',
    latitude: 42.797972,
    longitude: 23.446778,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0020',
    district: 'Нови Искър',
    address: 'с.Локорско - площад "Център"',
    latitude: 42.795333,
    longitude: 23.447361,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0021',
    district: 'Нови Искър',
    address: 'с.Чепинци - площад "Център"',
    latitude: 42.758667,
    longitude: 23.426722,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0022',
    district: 'Нови Искър',
    address: 'с.Чепинци - гробищен парк',
    latitude: 42.76,
    longitude: 23.43375,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0023',
    district: 'Нови Искър',
    address: 'с.Негован - гробищен парк',
    latitude: 42.767639,
    longitude: 23.408194,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0024',
    district: 'Нови Искър',
    address: 'с.Кубратово - площад "Център"',
    latitude: 42.773056,
    longitude: 23.362528,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0025',
    district: 'Нови Искър',
    address: 'с.Кубратово - гробищен парк',
    latitude: 42.767472,
    longitude: 23.356944,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: '"Сортови семена"ЕООД',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0026',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Курило - зад ОДЗ №135',
    latitude: 42.821111,
    longitude: 23.352611,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RNI-0027',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Кумарица - гробищен парк',
    latitude: 42.802111,
    longitude: 23.35,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0028',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Кумарица - площад "Свети дух"',
    latitude: 42.801389,
    longitude: 23.341083,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0029',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Славовци -площад "Център"',
    latitude: 42.791861,
    longitude: 23.334306,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0030',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Славовци - гробищен парк',
    latitude: 42.795333,
    longitude: 23.331778,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0031',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Гниляне - гробищен парк',
    latitude: 42.805306,
    longitude: 23.384639,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0032',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Курило - гробищен парк',
    latitude: 42.82875,
    longitude: 23.358889,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'Църковно настоятелство',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0033',
    district: 'Нови Искър',
    address: 'с.Световрачене - площад "Възраждане"',
    latitude: 42.782944,
    longitude: 23.390083,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RNI-0034',
    district: 'Нови Искър',
    address: 'гр.Нови Искър, кв.Кумарица - до старата баня',
    latitude: 42.801472,
    longitude: 23.341944,
    source: 'Минерална',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0001',
    district: 'Оборище',
    address: 'Парк "Заимов" - при ул. "Кракра" и бул. "Янко Сакъзов"',
    latitude: 42.696901,
    longitude: 23.338037,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0002',
    district: 'Оборище',
    address: 'Парк "Заимов" - централна алея',
    latitude: 42.697534,
    longitude: 23.340725,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0003',
    district: 'Оборище',
    address: 'Парк "Заимов" - зад театър "София"',
    latitude: 42.697067,
    longitude: 23.346064,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0004',
    district: 'Оборище',
    address: 'Докторска градина',
    latitude: 42.694603,
    longitude: 23.338644,
    source: 'Софийска вода',
    protectionStatus:
      'Чешмата няма индивидуален статут на единичен паметник на културата (недвижима културна ценност) по смисъла на Закона за културното наследство, но се намира в "Докторската градина", която е обявена за паметник на градинското и парковото изкуство.',
    isActive: true,
    status: 'За възстановяване',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0005',
    district: 'Оборище',
    address: 'Детска площадка на ул. "Буная" 29А',
    latitude: 42.696104,
    longitude: 23.352452,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0006',
    district: 'Оборище',
    address: 'Градина "Кюлуците"',
    latitude: 42.702148,
    longitude: 23.334822,
    source: 'Софийска вода',
    protectionStatus:
      'Чешма „Катеричката“ е официално заведена в Единния регистър на паметниците на Столична община като художествен паметник / елемент на градската среда (вид: Чешма/фонтан със скулптура – анималистична). Намира се в пределите на Градина "Кюлуците", която е паметник на градинското и парковото изкуство.',
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-ROB-0007',
    district: 'Оборище',
    address: 'Площад "Бански" - до Джамията "Баня Баши"',
    latitude: 42.699749,
    longitude: 23.322794,
    source: 'Софийска вода',
    protectionStatus:
      'Чешмата няма индивидуален статут на единичен паметник на културата (недвижима културна ценност) по смисъла на Закона за културното наследство, но попада в историческия център на София, който е обявен за археологически и архитектурен резерват и е част от групова културна ценност.',
    isActive: false,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-ROB-0008',
    district: 'Оборище',
    address:
      'Площад "Бански" - на фасадата на Музей за история на София (Централна минерална баня)',
    latitude: 42.699363,
    longitude: 23.323656,
    source: 'Минерална',
    protectionStatus:
      'Сградата на Музей за история на София (Централна минерална баня) е недвижима културна ценност с национално значение.',
    isActive: true,
    status: 'Добро',
    owner: 'Регионален исторически музей - София',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-ROB-0009',
    district: 'Оборище',
    address: 'Ул. "Искър" и ул. "Екзарх Йосиф"',
    latitude: 42.699945,
    longitude: 23.324151,
    source: 'Минерална',
    protectionStatus:
      'Минералният извор няма статут на архитектурен паметник, но попада в историческия център на София, който е обявен за археологически и архитектурен резерват и е част от групова културна ценност.',
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RSL-0001',
    district: 'Слатина',
    address: 'парк Гео Милев - кв. "Гео Милев"',
    latitude: 42.68625,
    longitude: 23.363556,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSL-0002',
    district: 'Слатина',
    address: 'ул. "Андрей Николов" № 24 - кв. "Гео Милев"',
    latitude: 42.680972,
    longitude: 23.365833,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSL-0003',
    district: 'Слатина',
    address: 'бул. "Ситняково" № 35 - кв. "Редута"',
    latitude: 42.693417,
    longitude: 23.355667,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RSL-0004',
    district: 'Слатина',
    address: 'пазар "Ситняково"',
    latitude: 42.684972,
    longitude: 23.353139,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'пазари Изток ЕАД',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RSL-0005',
    district: 'Слатина',
    address: 'пазар "Слатина"',
    latitude: 42.68141,
    longitude: 23.37356,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Няма информация',
    owner: 'пазари Изток ЕАД',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RML-0001',
    district: 'Младост',
    address: 'кв."Горубляне" - пред Читалище "Васил Левски"',
    latitude: 42.628282,
    longitude: 23.407969,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RML-0002',
    district: 'Младост',
    address: 'Парк "100 години София" - западна част',
    latitude: 42.644164,
    longitude: 23.370479,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RML-0003',
    district: 'Младост',
    address: 'Парк "100 години София" - източна част',
    latitude: 42.646469,
    longitude: 23.37157,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RML-0004',
    district: 'Младост',
    address: 'I-чешма на градинка при Lidl ж.к. "Младост 3"',
    latitude: 42.636937,
    longitude: 23.37375,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RML-0005',
    district: 'Младост',
    address: 'II-чешма на градинка при Lidl ж.к. "Младост 3"',
    latitude: 42.637056,
    longitude: 23.373457,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RML-0006',
    district: 'Младост',
    address: 'Парк "Сухото дере" в ж.к. "Младост 4"',
    latitude: 42.631017,
    longitude: 23.37949,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RML-0007',
    district: 'Младост',
    address: 'Източна чешма в парк "Сухото дере" в ж.к. "Младост 4"',
    latitude: 42.631611,
    longitude: 23.380254,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RML-0008',
    district: 'Младост',
    address: 'Народно читалще "Младост" в ж.к. "Младост 1"',
    latitude: 42.651769,
    longitude: 23.372524,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RST-0001',
    district: 'Студентски',
    address: 'Парк "Студентски", до Параклис, срещу УНСС',
    latitude: 42.652278,
    longitude: 23.347766,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RST-0002',
    district: 'Студентски',
    address: 'Парк "Студентски" -1',
    latitude: 42.655256,
    longitude: 23.349672,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За възстановяване',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RST-0003',
    district: 'Студентски',
    address: 'Парк "Студентски" -2',
    latitude: 42.653648,
    longitude: 23.349679,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За възстановяване',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RST-0004',
    district: 'Студентски',
    address: 'жк. "Дървеница", срещу Храм "Св. Георги"',
    latitude: 42.652953,
    longitude: 23.366063,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RST-0005',
    district: 'Студентски',
    address: 'Линеен парк на ул. "Проф. Иван Странски", жк. "Малинова долина"',
    latitude: 42.642607,
    longitude: 23.337458,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RST-0006',
    district: 'Студентски',
    address: 'Линеен парк на ул. "Проф. Иван Странски", жк. "Малинова долина"',
    latitude: 42.64236,
    longitude: 23.337435,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RST-0007',
    district: 'Студентски',
    address: 'МГУ "Св. Иван Рилски", ул. "Профл Боян Каменов"',
    latitude: 42.659945,
    longitude: 23.353064,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'МГУ "Св. Иван Рилски"',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0001',
    district: 'Кремиковци',
    address: 'кв. Сеславци, ул. "Стара планина" - на площада',
    latitude: 23.517655,
    longitude: 42.783045,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0002',
    district: 'Кремиковци',
    address: 'кв. Сеславци, ул. "Иван Боримечката"- гробищен парк',
    latitude: 23.516149,
    longitude: 42.785476,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0003',
    district: 'Кремиковци',
    address: 'кв. Кремиковци - гробищен парк',
    latitude: 23.51142,
    longitude: 42.782092,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0004',
    district: 'Кремиковци',
    address: 'кв. Враждебна, ул. "32-ра" - гробищен парк',
    latitude: 23.415348,
    longitude: 42.718476,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0005',
    district: 'Кремиковци',
    address: 'кв. Челопечене, ул. "Ридо" - гробищен парк',
    latitude: 23.481806,
    longitude: 42.730213,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0006',
    district: 'Кремиковци',
    address: 'кв. Ботунец, ул. "Зорница" - спортна зала',
    latitude: 23.505129,
    longitude: 42.73539,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0007',
    district: 'Кремиковци',
    address: 'с. Желява, ул. "24 май" - при храм "Св. Николай Чудотворец"',
    latitude: 23.606542,
    longitude: 42.752594,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0008',
    district: 'Кремиковци',
    address: 'с. Желява, ул. "Тоне Крайчев" - при детската площадка',
    latitude: 23.606908,
    longitude: 42.746151,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За ремонт',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0009',
    district: 'Кремиковци',
    address: 'с. Яна - гробищен парк',
    latitude: 23.566393,
    longitude: 42.728074,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0010',
    district: 'Кремиковци',
    address: 'с. Долни Богров, ул. "14-та" - гробищен парк',
    latitude: 23.485648,
    longitude: 42.699772,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0011',
    district: 'Кремиковци',
    address: 'с. Горни Богров, ул. "Васил Левски" - срещу кметството',
    latitude: 23.529844,
    longitude: 42.719126,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0012',
    district: 'Кремиковци',
    address: 'с. Горни Богров, ул. "Христо Ботев" - гробищен парк',
    latitude: 23.521148,
    longitude: 42.714103,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0013',
    district: 'Кремиковци',
    address: 'гр. Бухово, бул. "Никола Бонев" - гробищен парк',
    latitude: 23.571381,
    longitude: 42.76636,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RKR-0014',
    district: 'Кремиковци',
    address: 'гр. Бухово, бул. "Никола Бонев" - "СЕЛСКАТА ЧЕШМА"',
    latitude: 23.564786,
    longitude: 42.763727,
    source: 'Изворна',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RBA-0001',
    district: 'Банкя',
    address: 'Парк "Кестените" -  Централна минерална Баня I',
    latitude: 42.706967,
    longitude: 23.146837,
    source: 'Минерална',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RBA-0002',
    district: 'Банкя',
    address: 'Парк "Кестените" -  Централна минерална Баня II',
    latitude: 42.70704,
    longitude: 23.144482,
    source: 'Минерална',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RBA-0003',
    district: 'Банкя',
    address: 'Парк "Кестените" -  Централна минерална Баня III',
    latitude: 42.706834,
    longitude: 23.143814,
    source: 'Минерална',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RBA-0004',
    district: 'Банкя',
    address: 'Парк "Кестените" - Ротонда',
    latitude: 42.707458,
    longitude: 23.14371,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RBA-0005',
    district: 'Банкя',
    address: 'ул. Цар Симеон',
    latitude: 42.70585,
    longitude: 23.147896,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RBA-0006',
    district: 'Банкя',
    address: 'с. Иваняне',
    latitude: 42.706552,
    longitude: 23.181235,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Да',
  },
  {
    publicNumber: 'DF-RBA-0007',
    district: 'Банкя',
    address: 'Часовникова кула, ул. Княз БорисI, 2',
    latitude: 42.707436,
    longitude: 23.144525,
    source: 'Минерална',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0001',
    district: 'Триадица',
    address: 'Чешма парк "Здраве"- бул. "България"',
    latitude: 42.680984,
    longitude: 23.3067,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'район',
    activationType: 'Кран',
  },
  {
    publicNumber: 'DF-RTR-0002',
    district: 'Триадица',
    address: 'Чешма на ул. "Петър Парчевич" и бул. "Витоша"',
    latitude: 42.690789,
    longitude: 23.31955,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0003',
    district: 'Триадица',
    address: 'Чешма на бул. "Витоша" №131',
    latitude: 42.67571,
    longitude: 23.30929,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0004',
    district: 'Триадица',
    address: 'При х-л "Хилтън" на алея между м-я "Европейски съюз" и Моста на влюбените',
    latitude: 42.681008,
    longitude: 23.32072,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0005',
    district: 'Триадица',
    address: 'Чешма на детска площадка при музей "Земята и хората"',
    latitude: 42.680293,
    longitude: 23.3206,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0006',
    district: 'Триадица',
    address: 'Чешма парк "Буката" - "Момчето с козлето"',
    latitude: 42.688061,
    longitude: 23.31308,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Добро',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0007',
    district: 'Триадица',
    address: 'Чешма при читалище "Светлина"',
    latitude: 42.673387,
    longitude: 23.29929,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0008',
    district: 'Триадица',
    address: 'Чешма в парк "Боряна"- на ул. Забърде" и ул. "Бурел"',
    latitude: 42.675741,
    longitude: 23.31016,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0009',
    district: 'Триадица',
    address: 'Детска градинка срещу пазар "Иван Вазов", колелото на трамвай №1,6',
    latitude: 42.676377,
    longitude: 23.30472,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0010',
    district: 'Триадица',
    address: 'НДК - чешма бул. Витоша, зад пилоните',
    latitude: 42.685253,
    longitude: 23.31763,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Задоволително',
    owner: 'район',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0011',
    district: 'Триадица',
    address: 'НДК – чешма бул. "България" Юг за питейна вода',
    latitude: 42.682847,
    longitude: 23.31826,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0012',
    district: 'Триадица',
    address: 'НДК – чешма "Параклис" за питейна вода',
    latitude: 42.686487,
    longitude: 23.32027,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0013',
    district: 'Триадица',
    address: 'НДК – чешма пешеходна алея "Тройката" за питейна вода',
    latitude: 42.685814,
    longitude: 23.32002,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0014',
    district: 'Триадица',
    address:
      'Чешма в подлез на бул. „България“ и бул. „Гоце Делчев“ на изхода към ж.к. „Стрелбище“',
    latitude: 42.671982,
    longitude: 23.29519,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Отлично',
    owner: 'район',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0015',
    district: 'Триадица',
    address: 'Чешма при храм „Св. Георги Победоносец“, бул. „Патриарх Евтимий“ 90',
    latitude: 42.689478,
    longitude: 23.31569,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'За основен ремонт',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RTR-0016',
    district: 'Триадица',
    address: 'Чешма пред 29 ДКЦ, ул. "Георги Измирлиев" №8, кв. "Мотописта"',
    latitude: 42.6645,
    longitude: 23.29676,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Отлично',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RTR-0017',
    district: 'Триадица',
    address: 'ул. "Костенски водопад" при спирка на МГТ, авт. №76, пред бл. 242, кв. "Мотописта"',
    latitude: 42.663968,
    longitude: 23.29691,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: false,
    status: 'Отлично',
    owner: 'район',
    activationType: null,
  },
  {
    publicNumber: 'DF-RTR-0018',
    district: 'Триадица',
    address: 'Южен парк – чешма вход "Козяк"',
    latitude: 42.660678,
    longitude: 23.31328,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0019',
    district: 'Триадица',
    address: 'Южен парк – чешма вход "Гоце Делчев"',
    latitude: 42.665022,
    longitude: 23.30368,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
  {
    publicNumber: 'DF-RTR-0020',
    district: 'Триадица',
    address: 'Южен парк – чешма вход "Бяла черква"',
    latitude: 42.674615,
    longitude: 23.30826,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0021',
    district: 'Триадица',
    address: 'Южен парк – чешма "Английска поляна"',
    latitude: 42.673599,
    longitude: 23.30566,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Бутон',
  },
  {
    publicNumber: 'DF-RTR-0022',
    district: 'Триадица',
    address: 'Южен парк – чешма вход "Нишава"',
    latitude: 42.668987,
    longitude: 23.3044,
    source: 'Софийска вода',
    protectionStatus: null,
    isActive: true,
    status: 'Няма информация',
    owner: 'ОППГГ',
    activationType: 'Не',
  },
]

type QueryResultRow = Record<string, unknown>

/**
 * Minimal structural type satisfied by a Drizzle executor: the pooled
 * `payload.db.drizzle` instance, a transaction handle, and the `db` argument
 * Payload passes to migrations all match this shape.
 */
export interface DrizzleExecutor {
  execute(query: ReturnType<typeof sql>): Promise<{ rows: QueryResultRow[] }>
}

/** Public numbers of every seeded fountain, used to reverse the seed migration. */
export const seededFountainPublicNumbers: string[] = fountains.map(
  (fountain) => fountain.publicNumber
)

function getFirstId(rows: QueryResultRow[]): number | null {
  const value = rows[0]?.id

  if (typeof value === 'number') return value
  if (typeof value === 'string') return Number(value)

  return null
}

export async function seedDrinkingFountainRows(tx: DrizzleExecutor): Promise<number> {
  // Remove rows created by the previous global DF-0001 identifier format.
  await tx.execute(sql`
			DELETE FROM drinking_fountains
			WHERE public_number ~ '^DF-[0-9]{4}$'
		`)

  const sourceIds = new Map<string, number>()
  const ownerIds = new Map<string, number>()
  const districtIds = new Map<string, number>()

  const upsertSource = async (name: string): Promise<number> => {
    const cached = sourceIds.get(name)
    if (cached) return cached

    const result = await tx.execute(sql`
				INSERT INTO drinking_fountain_source (name, updated_at, created_at)
				VALUES (${name}, NOW(), NOW())
				ON CONFLICT (name)
				DO UPDATE SET updated_at = NOW()
				RETURNING id
			`)

    const id = getFirstId(result.rows as QueryResultRow[])
    if (!id) throw new Error(`Could not create or resolve source: "${name}"`)

    sourceIds.set(name, id)
    return id
  }

  const upsertOwner = async (name: string): Promise<number> => {
    const cached = ownerIds.get(name)
    if (cached) return cached

    const result = await tx.execute(sql`
				INSERT INTO fountain_owner (name, updated_at, created_at)
				VALUES (${name}, NOW(), NOW())
				ON CONFLICT (name)
				DO UPDATE SET updated_at = NOW()
				RETURNING id
			`)

    const id = getFirstId(result.rows as QueryResultRow[])
    if (!id) throw new Error(`Could not create or resolve owner: "${name}"`)

    ownerIds.set(name, id)
    return id
  }

  const getDistrictId = async (districtName: string): Promise<number | null> => {
    const cached = districtIds.get(districtName)
    if (cached) return cached

    const result = await tx.execute(sql`
				SELECT id
				FROM city_districts
				WHERE LOWER(TRIM(name)) = LOWER(TRIM(${districtName}))
				LIMIT 1
			`)

    const id = getFirstId(result.rows as QueryResultRow[])
    if (!id) return null

    districtIds.set(districtName, id)
    return id
  }

  for (const fountain of fountains) {
    const districtId = await getDistrictId(fountain.district)
    const sourceId = fountain.source ? await upsertSource(fountain.source) : null
    const ownerId = fountain.owner ? await upsertOwner(fountain.owner) : null

    await tx.execute(sql`
				INSERT INTO drinking_fountains (
					public_number,
					district_id,
					source_id,
					owner_id,
					address,
					location,
					status,
					activation_type,
					is_active,
					protection_status,
					external_link,
					updated_at,
					created_at
				)
				VALUES (
					${fountain.publicNumber},
					${districtId},
					${sourceId},
					${ownerId},
					${fountain.address},
					ST_SetSRID(ST_MakePoint(${fountain.longitude}, ${fountain.latitude}), 4326),
					${fountain.status}::"public"."enum_drinking_fountains_status",
					${fountain.activationType}::"public"."enum_drinking_fountains_activation_type",
					${fountain.isActive},
					${fountain.protectionStatus},
					NULL,
					NOW(),
					NOW()
				)
				ON CONFLICT (public_number)
				DO UPDATE SET
					district_id = EXCLUDED.district_id,
					source_id = EXCLUDED.source_id,
					owner_id = EXCLUDED.owner_id,
					address = EXCLUDED.address,
					location = EXCLUDED.location,
					status = EXCLUDED.status,
					activation_type = EXCLUDED.activation_type,
					is_active = EXCLUDED.is_active,
					protection_status = EXCLUDED.protection_status,
					external_link = EXCLUDED.external_link,
					updated_at = NOW()
			`)
  }

  return fountains.length
}

export async function seedDrinkingFountains(): Promise<void> {
  const payload = await getPayload({ config })
  const db = payload.db.drizzle

  const count = await db.transaction((tx) => seedDrinkingFountainRows(tx))

  payload.logger.info(`Seeded ${count} drinking fountains.`)
}

export async function seedDrinkingFountainsFromEnv(): Promise<void> {
  await seedDrinkingFountains()
}
