import { createRequire } from 'node:module'

/**
 * Seed drinking fountains + their lookup tables (source, status, owner,
 * activation type) from the official Sofia Municipality dataset.
 *
 * Run with: pnpm seed:drinking-fountains
 *
 * Deliberately uses a raw node-postgres connection (no Payload boot). The
 * schema must already exist — created by `pnpm dev` (dev push) or by migration
 * 20260715_000000_drinking_fountains — and city districts must be seeded
 * (migration 20260311_070751_districs_and_zones).
 *
 * Idempotent:
 *   - lookup rows use ON CONFLICT (name) DO NOTHING
 *   - fountains are only inserted when the table is empty
 *
 * The source dataset references districts by their business number (1–24). Rows
 * are loaded into a temp staging table and joined to city_districts on that
 * number to resolve the real relationship id.
 *
 * This file is generated from 02_insert_drinking_fountains.sql — regenerate it
 * rather than hand-editing the 151 fountain rows below.
 */

/** Minimal shape satisfied by a `pg` Client or Pool. */
export interface FountainSeedRunner {
  query: (text: string) => Promise<{ rows: Array<Record<string, unknown>> }>
}

const LOOKUPS_SQL = `
INSERT INTO drinking_fountain_source (name) VALUES
    ('Софийска вода'),
    ('Минерална'),
    ('Изворна') ON CONFLICT (name) DO NOTHING;

INSERT INTO fountain_status (name) VALUES
    ('Добро състояние'),
    ('Задоволително състояние'),
    ('Незадоволително състояние'),
    ('За ремонт'),
    ('В процес на ремонт'),
    ('Не работи'),
    ('Нова - очаква пускане'),
    ('Няма данни') ON CONFLICT (name) DO NOTHING;

INSERT INTO fountain_owner (name) VALUES
    ('"Сортови семена"ЕООД'),
    ('Водомер на църква Света Петка'),
    ('Водомер на църква Свети Георги Победоносец'),
    ('Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС'),
    ('МГУ "Св. Иван Рилски"'),
    ('Не се поддържа'),
    ('ОППГГ'),
    ('Регионален исторически музей - София'),
    ('Собственост на Пазари „Север“'),
    ('Софийска вода'),
    ('Църковно настоятелство'),
    ('водомер на Фреш Маркет'),
    ('кметството'),
    ('пазари Изток ЕАД'),
    ('район') ON CONFLICT (name) DO NOTHING;

INSERT INTO fountain_activation_type (name) VALUES
    ('Бутон'),
    ('Да (неопределен тип)'),
    ('Канелка'),
    ('Копче'),
    ('Кран'),
    ('Няма') ON CONFLICT (name) DO NOTHING;
`

const FOUNTAINS_SQL = `
    CREATE TEMP TABLE _df_import (
      district_num       integer,
      address            varchar,
      location           geometry(Point),
      source_id          integer,
      protection_status  varchar,
      is_active          boolean,
      status_id          integer,
      owner_id           integer,
      activation_type_id integer,
      external_link      varchar
    );

    INSERT INTO _df_import
      (district_num, address, location, source_id, protection_status, is_active, status_id, owner_id, activation_type_id, external_link)
    VALUES 
    (23, 'Храм "Св. София" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.330718, 42.696557), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'Храм "Св. Седмочисленици" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.32723721, 42.69021404), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (23, 'Градина "Св. Кл. Охридски" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.334444, 42.694333), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (23, 'Градина "Св. Кл. Охридски" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.333694, 42.694556), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (23, 'Борисова градина – чешма "Розариум" за питейна вода', ST_SetSRID(ST_MakePoint(23.337096, 42.687984), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'Борисова градина – чешма "Шестицата" за питейна вода', ST_SetSRID(ST_MakePoint(23.338819, 42.688416), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'Борисова градина – чешма детска площадка за питейна вода', ST_SetSRID(ST_MakePoint(23.339002, 42.687196), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'Борисова градина – чешма "Лилиите" за питейна вода', ST_SetSRID(ST_MakePoint(23.342949, 42.685101), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (23, 'Борисова градина – чешма "Читалнята" за питейна вода', ST_SetSRID(ST_MakePoint(23.344198, 42.68347), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (23, 'Борисова градина – чешма "Обсерваторията" за питейна вода', ST_SetSRID(ST_MakePoint(23.345349, 42.681689), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (23, 'Борисова градина – чешма "Полиграфията" за питейна вода', ST_SetSRID(ST_MakePoint(23.341938, 42.686771), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), NULL, NULL),
    (23, 'Народен театър – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.324887, 42.694749), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (23, 'Народен театър – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.3252454, 42.6953013), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, NULL, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), NULL, NULL, NULL),
    (23, 'БНБ', ST_SetSRID(ST_MakePoint(23.324889, 42.695735), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (23, 'НХГ Тамплиери', ST_SetSRID(ST_MakePoint(23.326626, 42.696726), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (23, 'НХГ Етнографски музей', ST_SetSRID(ST_MakePoint(23.328354, 42.696236), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (23, 'Руска Черква', ST_SetSRID(ST_MakePoint(23.329239, 42.695859), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (23, 'Гр. Кристал', ST_SetSRID(ST_MakePoint(23.329647, 42.694467), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'Св Патр. Евтимий', ST_SetSRID(ST_MakePoint(23.328427, 42.688356), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'пл. Райко Даскалов', ST_SetSRID(ST_MakePoint(23.322673, 42.692363), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (23, 'пред хотел "Рила"', ST_SetSRID(ST_MakePoint(23.323063, 42.694952), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (23, 'Княжевска градина', ST_SetSRID(ST_MakePoint(23.3339378, 42.690329), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (23, 'Площад "Португалия"', ST_SetSRID(ST_MakePoint(23.341982, 42.6900267), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (4, 'Парк "Възраждане" – чешма светофар за питейна вода', ST_SetSRID(ST_MakePoint(23.308608, 42.695931), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (4, 'Парк "Възраждане" – чешма до база за питейна вода', ST_SetSRID(ST_MakePoint(23.306637, 42.693967), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (4, 'Парк "Възраждане" – чешма до фонтана за питейна вода', ST_SetSRID(ST_MakePoint(23.306689, 42.694922), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (4, 'Парк "Възраждане" – чешма нова част I за питейна вода', ST_SetSRID(ST_MakePoint(23.306256, 42.696265), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (4, 'Парк "Възраждане" – чешма нова част II за питейна вода', ST_SetSRID(ST_MakePoint(23.305613, 42.695921), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (11, 'Пазар "Стара стена" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.329889, 42.683903), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, NULL, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (11, 'Баня Лозенец – чешма "Морената" за питейна вода', ST_SetSRID(ST_MakePoint(23.32246, 42.68276), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (24, 'Градина – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.315689, 42.689478), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), 'паметник на културата', NULL, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (24, 'Храм "Св. Георги" – 1 бр. чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.3207164, 42.6810076), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, NULL, (SELECT id FROM fountain_status WHERE name = 'Нова - очаква пускане'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (24, 'Южен парк II част – 1 бр. зад музея "Земята и хората" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.313275, 42.660678), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (24, 'Южен парк III част – чешма "Козяк" за питейна вода', ST_SetSRID(ST_MakePoint(23.303683, 42.665022), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (24, 'Южен парк III част – чешма вход "Гоце Делчев" за питейна вода', ST_SetSRID(ST_MakePoint(23.308263, 42.674615), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (24, 'Южен парк III част – чешма "Бяла черква" за питейна вода', ST_SetSRID(ST_MakePoint(23.305655, 42.673599), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (24, 'Южен парк III част – чешма "Английска поляна" за питейна вода', ST_SetSRID(ST_MakePoint(23.304417, 42.669003), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (24, 'Южен парк III част – чешма вход "Нишава" за питейна вода', ST_SetSRID(ST_MakePoint(23.318255, 42.682847), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (24, 'НДК (Южен парк I част) – чешма бул. "България" Юг за питейна вода', ST_SetSRID(ST_MakePoint(23.320267, 42.686487), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (24, 'НДК (Южен парк I част) – чешма "Параклис" за питейна вода', ST_SetSRID(ST_MakePoint(23.31935, 42.68827), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (24, 'НДК (Южен парк I част) – чешма пешеходна алея "Тройката" за питейна вода', ST_SetSRID(ST_MakePoint(23.320018, 42.685814), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'ОППГГ'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (24, 'НДК (Южен парк I част) – чешма площад за питейна вода', ST_SetSRID(ST_MakePoint(23.295192, 42.671982), 4326), (SELECT id FROM drinking_fountain_source WHERE name = NULL), 'данни от граждани', FALSE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), NULL, NULL, NULL),
    (3, 'Пазар "Връбница" – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.290755, 42.735781), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), NULL, NULL, NULL),
    (3, 'Бакърени гробища – чешма за питейна вода', ST_SetSRID(ST_MakePoint(23.280754, 42.73244), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), NULL, NULL, NULL),
    (3, 'Ж.к. Връбница 2, ул. Бели Дунав, бл.632', ST_SetSRID(ST_MakePoint(23.29222, 42.73667), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Собственост на Пазари „Север“'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'С.Мрамор, ул. Васил Левски - център', ST_SetSRID(ST_MakePoint(23.2747, 42.7854), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Софийска вода'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'С.Мрамор – гробищен парк (2 броя чешми)', ST_SetSRID(ST_MakePoint(23.2765, 42.806), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Софийска вода'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'С.Мрамор, до Фреш маркет', ST_SetSRID(ST_MakePoint(23.27394, 42.78609), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Не работи'), (SELECT id FROM fountain_owner WHERE name = 'водомер на Фреш Маркет'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'С.Мрамор, ул. Мичур срещу № 56Б', ST_SetSRID(ST_MakePoint(23.2688, 42.7882), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), NULL, (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (15, 'С.Мрамор, ул. Мичур №49', ST_SetSRID(ST_MakePoint(23.273, 42.7862), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), NULL, (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (15, 'С.Волуяк, ул. Зорница № 67', ST_SetSRID(ST_MakePoint(23.2432, 42.7738), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), NULL, (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (15, 'С.Волуяк, ул. Зорница № 49', ST_SetSRID(ST_MakePoint(23.2433, 42.7739), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Водомер на църква Свети Георги Победоносец'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'С.Волуяк- гробищен парк', ST_SetSRID(ST_MakePoint(23.2368, 42.7795), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Водомер на църква Света Петка'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'С.Волуяк, ул.Зорница № 22', ST_SetSRID(ST_MakePoint(23.2442, 42.7694), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'кметството'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (5, 'пред сградата на районната администрация на ул. "Атанас Далчев" №12', ST_SetSRID(ST_MakePoint(23.354266, 42.671519), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (5, 'на детска площадка пред блок 45 в жк. "Дианабад"', ST_SetSRID(ST_MakePoint(23.352669, 42.664245), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Задоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (5, 'на алея Яворов" до тенис кортовете в парк "Борисова градина"', ST_SetSRID(ST_MakePoint(23.346343, 42.677791), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (6, 'Парк "Света Троица"', ST_SetSRID(ST_MakePoint(23.295081, 42.705409), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Задоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (6, 'Вход на Западен парк - до спирка на градски транспорт', ST_SetSRID(ST_MakePoint(23.283317, 42.714991), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (6, 'Западен парк, на централната алея до първия кръг', ST_SetSRID(ST_MakePoint(23.281329, 42.713875), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Незадоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (6, 'Западен парк, на централната алея, до зона за скара', ST_SetSRID(ST_MakePoint(23.277098, 42.710303), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Незадоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (6, 'Западен парк, на централната алея, до детска площадка', ST_SetSRID(ST_MakePoint(23.276342, 42.709908), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Незадоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (6, 'Западен парк, на алея до криви огледала', ST_SetSRID(ST_MakePoint(23.282407, 42.711278), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Незадоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'Дирекция "Зелена система" Намира се в етап "Устойчивост" на проект, финансиран от ЕС'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (6, 'Бул. "Сливница", на ъгъла с ул. "Кукуш" ("Вентова чешма")', ST_SetSRID(ST_MakePoint(23.284081, 42.715201), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Не работи'), (SELECT id FROM fountain_owner WHERE name = 'Не се поддържа'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (14, 'Парк "Надежда" в ж.к."Лев Толстой"', ST_SetSRID(ST_MakePoint(23.309273, 42.722344), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'ж.к."Надежда" -1ч., бул."Ломско шосе" до метростанция "Надежда"', ST_SetSRID(ST_MakePoint(23.300934, 42.727772), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Задоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (14, 'ж.к."Надежда" -1ч., бул."Ломско шосе" № 36 пред магазин "DM"', ST_SetSRID(ST_MakePoint(23.302936, 42.726369), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'ж.к."Свобода", Северен парк до кучешка площадка', ST_SetSRID(ST_MakePoint(23.302319, 42.740109), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'Северен парк, до детска площадка "Морско дъно"', ST_SetSRID(ST_MakePoint(23.298026, 42.740202), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'Северен парк - централен вход от към ул."Ген. Никола Жеков"', ST_SetSRID(ST_MakePoint(23.298916, 42.738618), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'Северен парк до "Китайска беседка"', ST_SetSRID(ST_MakePoint(23.299172, 42.739989), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'Северен парк до "Амфи театър"', ST_SetSRID(ST_MakePoint(23.303725, 42.741449), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Задоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'ж.к."Надежда" - 3ч., до метростанция "Бели Дунав"', ST_SetSRID(ST_MakePoint(23.292836, 42.73483), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (14, 'ж.к."Надежда"-2ч., до бл.261', ST_SetSRID(ST_MakePoint(23.299514, 42.732506), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Нова - очаква пускане'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Балша - площад "Център"', ST_SetSRID(ST_MakePoint(23.269222, 42.848833), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (15, 'с.Балша - гробищен парк', ST_SetSRID(ST_MakePoint(23.268444, 42.844833), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Балша ул.Ст.планина - последна спирка', ST_SetSRID(ST_MakePoint(23.264722, 42.854556), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Доброславци - гробищен парк', ST_SetSRID(ST_MakePoint(23.288944, 42.823083), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Доброславци - център', ST_SetSRID(ST_MakePoint(23.283139, 42.822028), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Житен - площад "Център"', ST_SetSRID(ST_MakePoint(23.250917, 42.818194), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Житен - гробищен парк', ST_SetSRID(ST_MakePoint(23.257278, 42.815583), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Мировяне - ул."Ал.Константинов"', ST_SetSRID(ST_MakePoint(23.305, 42.788861), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (15, 'с.Мировяне - гробищен парк', ST_SetSRID(ST_MakePoint(23.297556, 42.797917), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Кътина - площад център', ST_SetSRID(ST_MakePoint(23.350639, 42.81425), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Кътина - градинка център', ST_SetSRID(ST_MakePoint(23.319278, 42.8455), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Кътина - при детска площадка ул.Езеро', ST_SetSRID(ST_MakePoint(23.322111, 42.843583), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Подгумер - парк "Изгрев"', ST_SetSRID(ST_MakePoint(23.405722, 42.80275), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Подгумер - гробищен парк', ST_SetSRID(ST_MakePoint(23.403694, 42.803944), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Подгумер - площад "Център"', ST_SetSRID(ST_MakePoint(23.403583, 42.802944), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Войнеговци - площад "Център"', ST_SetSRID(ST_MakePoint(23.40725, 42.804278), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Войнеговци - стадион', ST_SetSRID(ST_MakePoint(23.424028, 42.798583), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Войнеговци - гробищен парк', ST_SetSRID(ST_MakePoint(23.421611, 42.798333), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Локорско - гробищен парк', ST_SetSRID(ST_MakePoint(23.446778, 42.797972), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Локорско - площад "Център"', ST_SetSRID(ST_MakePoint(23.447361, 42.795333), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Чепинци - площад "Център"', ST_SetSRID(ST_MakePoint(23.426722, 42.758667), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Чепинци - гробищен парк', ST_SetSRID(ST_MakePoint(23.43375, 42.76), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Негован - гробищен парк', ST_SetSRID(ST_MakePoint(23.408194, 42.767639), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Кубратово - площад "Център"', ST_SetSRID(ST_MakePoint(23.362528, 42.773056), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Кубратово - гробищен парк', ST_SetSRID(ST_MakePoint(23.356944, 42.767472), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = '"Сортови семена"ЕООД'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Курило - зад ОДЗ №135', ST_SetSRID(ST_MakePoint(23.352611, 42.821111), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (15, 'гр.Нови Искър, кв.Кумарица - гробищен парк', ST_SetSRID(ST_MakePoint(23.35, 42.802111), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Кумарица - площад "Свети дух"', ST_SetSRID(ST_MakePoint(23.341083, 42.801389), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Славовци -площад "Център"', ST_SetSRID(ST_MakePoint(23.334306, 42.791861), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Славовци - гробищен парк', ST_SetSRID(ST_MakePoint(23.331778, 42.795333), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Гниляне - гробищен парк', ST_SetSRID(ST_MakePoint(23.384639, 42.805306), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Курило - гробищен парк', ST_SetSRID(ST_MakePoint(23.358889, 42.82875), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Църковно настоятелство'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'с.Световрачене - площад "Възраждане"', ST_SetSRID(ST_MakePoint(23.390083, 42.782944), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (15, 'гр.Нови Искър, кв.Кумарица - до старата баня', ST_SetSRID(ST_MakePoint(23.341944, 42.801472), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Минерална'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Парк "Заимов" - при ул. "Кракра" и бул. "Янко Сакъзов"', ST_SetSRID(ST_MakePoint(23.338037, 42.696901), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Парк "Заимов" - централна алея', ST_SetSRID(ST_MakePoint(23.340725, 42.697534), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Парк "Заимов" - зад театър "София"', ST_SetSRID(ST_MakePoint(23.346064, 42.697067), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Докторска градина', ST_SetSRID(ST_MakePoint(23.338644, 42.694603), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), 'Чешмата няма индивидуален статут на единичен паметник на културата (недвижима културна ценност) по смисъла на Закона за културното наследство, но се намира в "Докторската градина", която е обявена за паметник на градинското и парковото изкуство.', TRUE, (SELECT id FROM fountain_status WHERE name = 'В процес на ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Детска площадка на ул. "Буная" 29А', ST_SetSRID(ST_MakePoint(23.352452, 42.696104), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Градина "Кюлуците"', ST_SetSRID(ST_MakePoint(23.334822, 42.702148), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), 'Чешма „Катеричката“ е официално заведена в Единния регистър на паметниците на Столична община като художествен паметник / елемент на градската среда (вид: Чешма/фонтан със скулптура – анималистична). Намира се в пределите на Градина "Кюлуците", която е паметник на градинското и парковото изкуство.', TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (17, 'Площад "Бански" - до Джамията "Баня Баши"', ST_SetSRID(ST_MakePoint(23.322794, 42.699749), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), 'Чешмата няма индивидуален статут на единичен паметник на културата (недвижима културна ценност) по смисъла на Закона за културното наследство, но попада в историческия център на София, който е обявен за археологически и архитектурен резерват и е част от групова културна ценност.', FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (17, 'Площад "Бански" - на фасадата на Музей за история на София (Централна минерална баня)', ST_SetSRID(ST_MakePoint(23.323656, 42.699363), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Минерална'), 'Сградата на Музей за история на София (Централна минерална баня) е недвижима културна ценност с национално значение.', TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'Регионален исторически музей - София'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (17, 'Ул. "Искър" и ул. "Екзарх Йосиф"', ST_SetSRID(ST_MakePoint(23.324151, 42.699945), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Минерална'), 'Минералният извор няма статут на архитектурен паметник, но попада в историческия център на София, който е обявен за археологически и архитектурен резерват и е част от групова културна ценност.', TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (21, 'парк Гео Милев - кв. "Гео Милев"', ST_SetSRID(ST_MakePoint(23.363556, 42.68625), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Задоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Канелка'), NULL),
    (21, 'ул. "Андрей Николов" № 24 - кв. "Гео Милев"', ST_SetSRID(ST_MakePoint(23.365833, 42.680972), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Канелка'), NULL),
    (21, 'бул. "Ситняково" № 35 - кв. "Редута"', ST_SetSRID(ST_MakePoint(23.355667, 42.693417), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Задоволително състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Канелка'), NULL),
    (21, 'пазар "Ситняково"', ST_SetSRID(ST_MakePoint(23.353139, 42.684972), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'пазари Изток ЕАД'), (SELECT id FROM fountain_activation_type WHERE name = 'Копче'), NULL),
    (21, 'пазар "Слатина"', ST_SetSRID(ST_MakePoint(23.37356, 42.68141), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'Няма данни'), (SELECT id FROM fountain_owner WHERE name = 'пазари Изток ЕАД'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (13, 'кв."Горубляне" - пред Читалище "Васил Левски"', ST_SetSRID(ST_MakePoint(23.407969, 42.628282), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Кран'), NULL),
    (13, 'Парк "100 години София" - западна част', ST_SetSRID(ST_MakePoint(23.370479, 42.644164), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (13, 'Парк "100 години София" - източна част', ST_SetSRID(ST_MakePoint(23.37157, 42.646469), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (13, 'I-чешма на градинка при Lidl ж.к. "Младост 3"', ST_SetSRID(ST_MakePoint(23.37375, 42.636937), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (13, 'II-чешма на градинка при Lidl ж.к. "Младост 3"', ST_SetSRID(ST_MakePoint(23.373457, 42.637056), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (13, 'Парк "Сухото дере" в ж.к. "Младост 4"', ST_SetSRID(ST_MakePoint(23.37949, 42.631017), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Бутон'), NULL),
    (13, 'Източна чешма в парк "Сухото дере" в ж.к. "Младост 4"', ST_SetSRID(ST_MakePoint(23.380254, 42.631611), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (13, 'Народно читалще "Младост" в ж.к. "Младост 1"', ST_SetSRID(ST_MakePoint(23.372524, 42.651769), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), NULL, NULL),
    (22, 'Парк "Студентски", до Параклис, срещу УНСС', ST_SetSRID(ST_MakePoint(23.347766, 42.652278), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (22, 'Парк "Студентски" -1', ST_SetSRID(ST_MakePoint(23.349672, 42.655256), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), NULL, NULL, NULL),
    (22, 'Парк "Студентски" -2', ST_SetSRID(ST_MakePoint(23.349679, 42.653648), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), NULL, NULL, NULL),
    (22, 'жк. "Дървеница", срещу Храм "Св. Георги"', ST_SetSRID(ST_MakePoint(23.366063, 42.652953), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Няма'), NULL),
    (22, 'Линеен парк на ул. "Проф. Иван Странски", жк. "Малинова долина"', ST_SetSRID(ST_MakePoint(23.337458, 42.642607), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (22, 'Линеен парк на ул. "Проф. Иван Странски", жк. "Малинова долина"', ST_SetSRID(ST_MakePoint(23.337435, 42.64236), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (22, 'МГУ "Св. Иван Рилски", ул. "Профл Боян Каменов"', ST_SetSRID(ST_MakePoint(23.353064, 42.659945), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'МГУ "Св. Иван Рилски"'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'кв. Сеславци, ул. "Стара планина" - на площада', ST_SetSRID(ST_MakePoint(23.517655, 42.783045), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'кв. Сеславци, ул. "Иван Боримечката"- гробищен парк', ST_SetSRID(ST_MakePoint(23.516149, 42.785476), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'кв. Кремиковци - гробищен парк', ST_SetSRID(ST_MakePoint(23.51142, 42.782092), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'кв. Враждебна, ул. "32-ра" - гробищен парк', ST_SetSRID(ST_MakePoint(23.415348, 42.718476), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'кв. Челопечене, ул. "Ридо" - гробищен парк', ST_SetSRID(ST_MakePoint(23.481806, 42.730213), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'кв. Ботунец, ул. "Зорница" - спортна зала', ST_SetSRID(ST_MakePoint(23.505129, 42.73539), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'с. Желява, ул. "24 май" - при храм "Св. Николай Чудотворец"', ST_SetSRID(ST_MakePoint(23.606542, 42.752594), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'с. Желява, ул. "Тоне Крайчев" - при детската площадка', ST_SetSRID(ST_MakePoint(23.606908, 42.746151), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, FALSE, (SELECT id FROM fountain_status WHERE name = 'За ремонт'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'с. Яна - гробищен парк', ST_SetSRID(ST_MakePoint(23.566393, 42.728074), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'с. Долни Богров, ул. "14-та" - гробищен парк', ST_SetSRID(ST_MakePoint(23.485648, 42.699772), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'с. Горни Богров, ул. "Васил Левски" - срещу кметството', ST_SetSRID(ST_MakePoint(23.529844, 42.719126), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'с. Горни Богров, ул. "Христо Ботев" - гробищен парк', ST_SetSRID(ST_MakePoint(23.521148, 42.714103), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Софийска вода'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'гр. Бухово, бул. "Никола Бонев" - гробищен парк', ST_SetSRID(ST_MakePoint(23.571381, 42.76636), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL),
    (10, 'гр. Бухово, бул. "Никола Бонев" - "СЕЛСКАТА ЧЕШМА"', ST_SetSRID(ST_MakePoint(23.564786, 42.763727), 4326), (SELECT id FROM drinking_fountain_source WHERE name = 'Изворна'), NULL, TRUE, (SELECT id FROM fountain_status WHERE name = 'Добро състояние'), (SELECT id FROM fountain_owner WHERE name = 'район'), (SELECT id FROM fountain_activation_type WHERE name = 'Да (неопределен тип)'), NULL);

    INSERT INTO drinking_fountains
      (district_id, address, location, source_id, protection_status, is_active, status_id, owner_id, activation_type_id, external_link)
    SELECT cd.id, i.address, i.location, i.source_id, i.protection_status, i.is_active, i.status_id, i.owner_id, i.activation_type_id, i.external_link
    FROM _df_import i
    JOIN city_districts cd ON cd.district_id = i.district_num;

    -- Assign public identifiers (DF-<district code>-<zero-padded id>)
    UPDATE drinking_fountains df
    SET public_number = 'DF-' || COALESCE(cd.code, 'XXX') || '-' || LPAD(df.id::text, 4, '0')
    FROM city_districts cd
    WHERE cd.id = df.district_id AND df.public_number IS NULL;

    UPDATE drinking_fountains
    SET public_number = 'DF-XXX-' || LPAD(id::text, 4, '0')
    WHERE public_number IS NULL;

    DROP TABLE _df_import;
`

async function count(db: FountainSeedRunner): Promise<number> {
  const res = await db.query('SELECT COUNT(*)::int AS count FROM drinking_fountains')
  return Number((res.rows[0] as { count: number } | undefined)?.count ?? 0)
}

/**
 * Seed using an existing connection (`pg` Client/Pool, or anything exposing
 * `query(text)`). Runs the lookups then the fountains unless already present.
 */
export async function seedDrinkingFountains(db: FountainSeedRunner): Promise<void> {
  console.log('🌱 Seeding drinking fountain lookups…')
  await db.query(LOOKUPS_SQL)

  if ((await count(db)) > 0) {
    console.log('⏭️  Skipping fountains — table already has rows')
    console.log('✨ Seeding complete!')
    return
  }

  console.log('🌱 Seeding drinking fountains…')
  await db.query(FOUNTAINS_SQL)
  console.log(`✅ Seeded ${await count(db)} drinking fountains`)
  console.log('✨ Seeding complete!')
}

type PgClient = FountainSeedRunner & {
  connect: () => Promise<void>
  end: () => Promise<void>
}

// Structural type for the bits of `pg` we use — avoids a dependency on @types/pg.
type PgModule = { Client: new (config: { connectionString: string }) => PgClient }

/**
 * Convenience runner: opens a `pg` connection from `process.env.DATABASE_URI`,
 * seeds, and closes. `pg` is loaded via createRequire because its legacy CJS
 * `main` does not resolve under ESM/tsx.
 */
export async function seedDrinkingFountainsFromEnv(): Promise<void> {
  const connectionString = process.env.DATABASE_URI
  if (!connectionString) {
    throw new Error('DATABASE_URI is not set (expected in .env.local)')
  }
  const require = createRequire(import.meta.url)
  const { Client } = require('pg') as PgModule
  const client = new Client({ connectionString })
  await client.connect()
  try {
    await seedDrinkingFountains(client)
  } finally {
    await client.end()
  }
}
