name: 🚀 DevOps/Infrastructure
description: DevOps-related issues, CI/CD, infrastructure, monitoring, or deployment problems
title: "[DevOps]: "
labels: ["devops", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        These issues are for improving development workflows, infrastructure, deployment processes, and operational reliability.

  - type: dropdown
    id: component
    attributes:
      label: DevOps Area
      description: Which DevOps area does this issue relate to?
      options:
        - CI/CD Pipeline
        - Infrastructure as Code
        - Monitoring/Alerting
        - Logging
        - Deployment Process
        - Security Practices
        - Development Environment Setup
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the DevOps issue or improvement needed
      placeholder: |
        Example: The CI/CD pipeline takes 15 minutes to complete, we should optimize the build steps.
    validations:
      required: true
